import { put } from "@vercel/blob"
import { headers } from "next/headers"
import { NextRequest, NextResponse } from "next/server"
import { sql } from "drizzle-orm"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { compareMetadata, normalizeMetadata, parseWorkbook, requiredSections, toCsv } from "@/lib/migration-analysis"
import { packageSummary, parseExportPackage } from "@/lib/aegis-export-package"

const adminRoles = new Set(["ADMIN", "ADMIN SYSTEM", "SYSTEM ADMINISTRATOR", "MANAGEMENT", "HSE ADMIN"])
async function requireAdmin() { const session = await auth.api.getSession({ headers: await headers() }); const role = String((session?.user as unknown as { role?: string } | undefined)?.role || "").toUpperCase(); if (!session?.user || !adminRoles.has(role)) throw new Error("FORBIDDEN") }
async function neonMetadata() { const tables = await db.execute(sql`SELECT table_schema AS schema, table_name AS name FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name`); const columns = await db.execute(sql`SELECT table_schema AS schema, table_name AS table, column_name AS column, data_type AS type, is_nullable, column_default AS default_value FROM information_schema.columns WHERE table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name, ordinal_position`); const keys = await db.execute(sql`SELECT tc.table_schema AS schema, tc.table_name AS table, tc.constraint_type AS type, tc.constraint_name AS constraint FROM information_schema.table_constraints tc WHERE tc.table_schema NOT IN ('neon_auth','pg_catalog','information_schema') AND tc.constraint_type IN ('PRIMARY KEY','FOREIGN KEY','UNIQUE') ORDER BY tc.table_schema, tc.table_name`); const keyRows = keys.rows as Array<{ type?: string }>; return normalizeMetadata({ tables: tables.rows, columns: columns.rows, "primary keys": keyRows.filter((r) => r.type === "PRIMARY KEY"), "foreign keys": keyRows.filter((r) => r.type === "FOREIGN KEY"), "unique constraints": keyRows.filter((r) => r.type === "UNIQUE") }, "neon") }
async function analyze(raw: Record<string, unknown>) { const aegis = normalizeMetadata(raw); const missing = requiredSections.filter((section) => !aegis.available[section]); if (!aegis.database || !aegis.available.tables || !aegis.available.columns) throw new Error(`Missing metadata sections: ${missing.join(", ")}`); const neon = await neonMetadata(); return { aegis, neon, analysis: compareMetadata(aegis, neon) } }
export async function POST(request: NextRequest) { try { await requireAdmin(); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ error: "Export package is required." }, { status: 400 }); if (file.size > 250 * 1024 * 1024) return NextResponse.json({ error: "Package must be 250 MB or smaller." }, { status: 413 }); const buffer = Buffer.from(await file.arrayBuffer()); let result: { raw: Record<string, unknown>; summary?: Record<string, unknown>; packageValidated: boolean }; if (file.name.toLowerCase().endsWith(".zip")) { const pkg = await parseExportPackage(buffer); result = { raw: { database: [pkg.database], tables: pkg.tables, columns: pkg.columns, "primary keys": pkg.primaryKeys, "foreign keys": pkg.foreignKeys, indexes: pkg.indexes, summary: [packageSummary(pkg)] }, summary: packageSummary(pkg), packageValidated: true } } else { const extension = `.${file.name.split(".").pop()?.toLowerCase()}`; if (![".json", ".csv", ".xlsx", ".txt"].includes(extension)) return NextResponse.json({ error: "Upload a validated ZIP export package or metadata file." }, { status: 415 }); result = { raw: parseWorkbook(buffer, extension) as Record<string, unknown>, packageValidated: false }; } const analysis = await analyze(result.raw); const blob = await put(`aegis-exports/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`, buffer, { access: "private", addRandomSuffix: true }); return NextResponse.json({ file: { name: file.name, size: file.size, uploadedAt: new Date().toISOString(), pathname: blob.pathname }, packageValidated: result.packageValidated, exportSummary: result.summary ?? null, ...analysis }) } catch (error) { const status = error instanceof Error && error.message === "FORBIDDEN" ? 403 : 422; return NextResponse.json({ error: status === 403 ? "Administrator access required." : error instanceof Error ? error.message : "Export package validation failed." }, { status }) } }
export async function GET() { try { await requireAdmin(); return NextResponse.json({ neon: await neonMetadata() }) } catch { return NextResponse.json({ error: "Administrator access required." }, { status: 403 }) } }
export async function PATCH(request: NextRequest) { try { await requireAdmin(); const { format, section, data } = await request.json(); const rows = Array.isArray(data) ? data : []; if (!["json", "csv"].includes(format)) return NextResponse.json({ error: "Only JSON and CSV exports are supported." }, { status: 400 }); const body = format === "csv" ? toCsv(rows) : JSON.stringify({ section, rows }, null, 2); return new NextResponse(body, { headers: { "Content-Type": format === "csv" ? "text/csv" : "application/json", "Content-Disposition": `attachment; filename="${section || "analysis"}.${format}"` } }) } catch { return NextResponse.json({ error: "Export failed." }, { status: 500 }) } }
