import { put } from "@vercel/blob"
import { createHash, randomUUID } from "node:crypto"
import { headers } from "next/headers"
import { NextRequest, NextResponse } from "next/server"
import { sql } from "drizzle-orm"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { compareMetadata, normalizeMetadata, parseWorkbook, requiredSections, toCsv } from "@/lib/migration-analysis"
import { packageSummary, parseExportPackage } from "@/lib/aegis-export-package"

const adminRoles = new Set(["ADMIN", "ADMIN SYSTEM", "SYSTEM ADMINISTRATOR", "MANAGEMENT", "HSE ADMIN"])
async function requireAdmin() { const session = await auth.api.getSession({ headers: await headers() }); const role = String((session?.user as unknown as { role?: string } | undefined)?.role || "").toUpperCase(); if (!session?.user || !adminRoles.has(role)) throw new Error("FORBIDDEN") }
async function neonMetadata() { const tables = await db.execute(sql`SELECT table_schema AS schema, table_name AS name FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name`); const columns = await db.execute(sql`SELECT table_schema AS schema, table_name AS table, column_name AS column, data_type AS type, is_nullable, column_default AS default_value FROM information_schema.columns WHERE table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name, ordinal_position`); const keys = await db.execute(sql`SELECT tc.table_schema AS schema, tc.table_name AS table, tc.constraint_type AS type, tc.constraint_name AS constraint FROM information_schema.table_constraints tc WHERE tc.table_schema NOT IN ('neon_auth','pg_catalog','information_schema') AND tc.constraint_type IN ('PRIMARY KEY','FOREIGN KEY','UNIQUE') ORDER BY tc.table_schema, tc.table_name`); const keyRows = keys.rows as Array<{ type?: string }>; return normalizeMetadata({ tables: tables.rows, columns: columns.rows, "primary keys": keyRows.filter((r) => r.type === "PRIMARY KEY"), "foreign keys": keyRows.filter((r) => r.type === "FOREIGN KEY"), "unique constraints": keyRows.filter((r) => r.type === "UNIQUE") }, "neon") }
async function analyze(raw: Record<string, unknown>) { const aegis = normalizeMetadata(raw); const missing = requiredSections.filter((section) => !aegis.available[section]); if (!aegis.database || !aegis.available.tables || !aegis.available.columns) throw new Error(`Missing metadata sections: ${missing.join(", ")}`); const neon = await neonMetadata(); return { aegis, neon, analysis: compareMetadata(aegis, neon) } }
async function persistValidatedPackage(pkg: Awaited<ReturnType<typeof parseExportPackage>>, packageSha256: string, uploadedBy: string) { const manifest = pkg.manifest; const database = pkg.database; const sourceDatabase = String(manifest.database ?? database.database_name ?? "Aegis_XOM"); const sourceServer = String(manifest.server ?? database.server_name ?? "localhost\\SQLEXPRESS"); const importId = randomUUID(); const summary = packageSummary(pkg); await db.transaction(async (tx) => { await tx.execute(sql`INSERT INTO public.aegis_migration_import (id, source_database, source_server, package_sha256, manifest, status, uploaded_by) VALUES (${importId}, ${sourceDatabase}, ${sourceServer}, ${packageSha256}, ${JSON.stringify({ ...manifest, summary })}::jsonb, 'validated', ${uploadedBy})`); for (const table of pkg.tables) { const schema = String(table.schema_name ?? table.schema ?? "dbo"); const name = String(table.table_name ?? table.name ?? ""); const tableKey = `table_data/${schema}__${name}.json`; const data = pkg.tableData[tableKey] ?? []; for (const row of data) { const rowJson = JSON.stringify(row); const rowHash = createHash("sha256").update(rowJson).digest("hex"); const sourceKey = Object.entries(row).filter(([key]) => /(^id$|_id$|key$|number$)/i.test(key)).map(([key, value]) => `${key}=${String(value)}`).join("|").slice(0, 500) || null; await tx.execute(sql`INSERT INTO public.aegis_migration_record (id, import_id, source_schema, source_table, source_key, source_row, row_hash) VALUES (${randomUUID()}, ${importId}, ${schema}, ${name}, ${sourceKey}, ${rowJson}::jsonb, ${rowHash}) ON CONFLICT DO NOTHING`); } } for (const column of pkg.columns) { const schema = String(column.schema_name ?? column.schema ?? "dbo"); const table = String(column.table_name ?? column.table ?? ""); const columnName = String(column.column_name ?? column.column ?? ""); await tx.execute(sql`INSERT INTO public.aegis_migration_mapping (id, import_id, source_schema, source_table, source_column, mapping_type, confidence, review_status, notes) VALUES (${randomUUID()}, ${importId}, ${schema}, ${table}, ${columnName}, 'unconfirmed', 0, 'pending', 'Awaiting human review against Neon schema') ON CONFLICT DO NOTHING`); } }); return { importId, summary } }
export async function POST(request: NextRequest) { try { await requireAdmin(); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ error: "Export package is required." }, { status: 400 }); if (file.size > 250 * 1024 * 1024) return NextResponse.json({ error: "Package must be 250 MB or smaller." }, { status: 413 }); const buffer = Buffer.from(await file.arrayBuffer()); let pkg: Awaited<ReturnType<typeof parseExportPackage>> | null = null; let result: { raw: Record<string, unknown>; summary?: Record<string, unknown>; packageValidated: boolean }; if (file.name.toLowerCase().endsWith(".zip")) { pkg = await parseExportPackage(buffer); result = { raw: { database: [pkg.database], tables: pkg.tables, columns: pkg.columns, "primary keys": pkg.primaryKeys, "foreign keys": pkg.foreignKeys, indexes: pkg.indexes, summary: [packageSummary(pkg)] }, summary: packageSummary(pkg), packageValidated: true } } else { const extension = `.${file.name.split(".").pop()?.toLowerCase()}`; if (![".json", ".csv", ".xlsx", ".txt"].includes(extension)) return NextResponse.json({ error: "Upload a validated ZIP export package or metadata file." }, { status: 415 }); result = { raw: parseWorkbook(buffer, extension) as Record<string, unknown>, packageValidated: false }; } const analysis = await analyze(result.raw); const blob = await put(`aegis-exports/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`, buffer, { access: "private", addRandomSuffix: true }); const uploadedBy = String((await auth.api.getSession({ headers: await headers() }))?.user?.id ?? "admin"); const packageSha256 = createHash("sha256").update(buffer).digest("hex"); const persisted = result.packageValidated && pkg ? await persistValidatedPackage(pkg, packageSha256, uploadedBy) : null; return NextResponse.json({ file: { name: file.name, size: file.size, uploadedAt: new Date().toISOString(), pathname: blob.pathname }, packageValidated: result.packageValidated, packageSha256, importId: persisted?.importId ?? null, exportSummary: persisted?.summary ?? result.summary ?? null, ...analysis }) } catch (error) { const status = error instanceof Error && error.message === "FORBIDDEN" ? 403 : 422; return NextResponse.json({ error: status === 403 ? "Administrator access required." : error instanceof Error ? error.message : "Export package validation failed." }, { status }) } }
export async function GET() { try { await requireAdmin(); return NextResponse.json({ neon: await neonMetadata() }) } catch { return NextResponse.json({ error: "Administrator access required." }, { status: 403 }) } }
export async function PATCH(request: NextRequest) { try { await requireAdmin(); const { format, section, data } = await request.json(); const rows = Array.isArray(data) ? data : []; if (!["json", "csv"].includes(format)) return NextResponse.json({ error: "Only JSON and CSV exports are supported." }, { status: 400 }); const body = format === "csv" ? toCsv(rows) : JSON.stringify({ section, rows }, null, 2); return new NextResponse(body, { headers: { "Content-Type": format === "csv" ? "text/csv" : "application/json", "Content-Disposition": `attachment; filename="${section || "analysis"}.${format}"` } }) } catch { return NextResponse.json({ error: "Export failed." }, { status: 500 }) } }
