import { put } from "@vercel/blob"
import { headers } from "next/headers"
import { NextRequest, NextResponse } from "next/server"
import { sql } from "drizzle-orm"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import { compareMetadata, normalizeMetadata, parseWorkbook, toCsv } from "@/lib/migration-analysis"

const adminRoles = new Set(["ADMIN", "ADMIN SYSTEM", "SYSTEM ADMINISTRATOR", "MANAGEMENT", "HSE ADMIN"])
async function requireAdmin() { const session = await auth.api.getSession({ headers: await headers() }); const role = String((session?.user as unknown as { role?: string } | undefined)?.role || "").toUpperCase(); if (!session?.user || !adminRoles.has(role)) throw new Error("FORBIDDEN") }
async function neonMetadata() {
  const tables = await db.execute(sql`SELECT table_schema AS schema, table_name AS name FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name`)
  const columns = await db.execute(sql`SELECT table_schema AS schema, table_name AS table, column_name AS column, data_type AS type, is_nullable, column_default AS default_value FROM information_schema.columns WHERE table_schema NOT IN ('neon_auth','pg_catalog','information_schema') ORDER BY table_schema, table_name, ordinal_position`)
  const keys = await db.execute(sql`SELECT tc.table_schema AS schema, tc.table_name AS table, tc.constraint_type AS type, tc.constraint_name AS constraint FROM information_schema.table_constraints tc WHERE tc.table_schema NOT IN ('neon_auth','pg_catalog','information_schema') AND tc.constraint_type IN ('PRIMARY KEY','FOREIGN KEY','UNIQUE') ORDER BY tc.table_schema, tc.table_name`)
  const keyRows = keys.rows as Array<{ type?: string }>
  return normalizeMetadata({ tables: tables.rows, columns: columns.rows, "primary keys": keyRows.filter((r) => r.type === "PRIMARY KEY"), "foreign keys": keyRows.filter((r) => r.type === "FOREIGN KEY"), "unique constraints": keyRows.filter((r) => r.type === "UNIQUE") }, "neon")
}
export async function POST(request: NextRequest) { try { await requireAdmin(); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return NextResponse.json({ error: "Metadata file is required." }, { status: 400 }); const extension = `.${file.name.split(".").pop()?.toLowerCase()}`; if (![".json", ".csv", ".xlsx", ".txt"].includes(extension)) return NextResponse.json({ error: "Only JSON, CSV, XLSX, and TXT files are supported." }, { status: 415 }); if (file.size > 25 * 1024 * 1024) return NextResponse.json({ error: "File must be 25 MB or smaller." }, { status: 413 }); const buffer = Buffer.from(await file.arrayBuffer()); const blob = await put(`aegis-metadata/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`, buffer, { access: "private", addRandomSuffix: true }); const aegis = normalizeMetadata(parseWorkbook(buffer, extension) as Record<string, unknown>); const neon = await neonMetadata(); const analysis = compareMetadata(aegis, neon); return NextResponse.json({ file: { name: file.name, size: file.size, uploadedAt: new Date().toISOString(), pathname: blob.pathname }, aegis, neon, analysis }) } catch (error) { const status = error instanceof Error && error.message === "FORBIDDEN" ? 403 : 500; return NextResponse.json({ error: status === 403 ? "Administrator access required." : "Analysis failed. Verify the metadata file and Neon connection." }, { status }) } }
export async function GET() { try { await requireAdmin(); return NextResponse.json({ neon: await neonMetadata() }) } catch { return NextResponse.json({ error: "Administrator access required." }, { status: 403 }) } }
export async function PATCH(request: NextRequest) { try { await requireAdmin(); const { format, section, data } = await request.json(); const rows = Array.isArray(data) ? data : []; if (!["json", "csv"].includes(format)) return NextResponse.json({ error: "Only JSON and CSV exports are supported." }, { status: 400 }); const body = format === "csv" ? toCsv(rows) : JSON.stringify({ section, rows }, null, 2); return new NextResponse(body, { headers: { "Content-Type": format === "csv" ? "text/csv" : "application/json", "Content-Disposition": `attachment; filename="${section || "analysis"}.${format}"` } }) } catch { return NextResponse.json({ error: "Export failed." }, { status: 500 }) } }
