import sql from "mssql"

const readOnlyQueries = {
  tables: `SELECT s.name AS schema_name, t.name AS table_name, SUM(CASE WHEN p.index_id IN (0, 1) THEN p.rows ELSE 0 END) AS record_count FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id LEFT JOIN sys.partitions p ON p.object_id = t.object_id WHERE t.is_ms_shipped = 0 GROUP BY s.name, t.name ORDER BY s.name, t.name`,
  columns: `SELECT s.name AS schema_name, t.name AS table_name, c.column_id AS column_order, c.name AS column_name, ty.name AS sql_server_data_type, CASE WHEN ty.name IN ('nvarchar','nchar') AND c.max_length <> -1 THEN c.max_length / 2 ELSE c.max_length END AS max_length, c.precision, c.scale, c.is_nullable, c.is_identity, c.is_computed, dc.definition AS default_value, cc.definition AS computed_definition, c.collation_name FROM sys.columns c JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.types ty ON ty.user_type_id = c.user_type_id LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id LEFT JOIN sys.computed_columns cc ON cc.object_id = c.object_id AND cc.column_id = c.column_id ORDER BY s.name, t.name, c.column_id`,
  primaryKeys: `SELECT kc.name AS constraint_name, s.name AS schema_name, t.name AS table_name, c.name AS column_name, ic.key_ordinal AS key_order, i.type_desc AS index_type FROM sys.key_constraints kc JOIN sys.tables t ON t.object_id = kc.parent_object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.indexes i ON i.object_id = kc.parent_object_id AND i.index_id = kc.unique_index_id JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id WHERE kc.type = 'PK' ORDER BY s.name, t.name, kc.name, ic.key_ordinal`,
  foreignKeys: `SELECT fk.name AS constraint_name, ps.name AS parent_schema, pt.name AS parent_table, pc.name AS parent_column, rs.name AS referenced_schema, rt.name AS referenced_table, rc.name AS referenced_column, fkc.constraint_column_id AS column_order, fk.delete_action_desc AS on_delete_action, fk.update_action_desc AS on_update_action, fk.is_disabled, fk.is_not_trusted FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id JOIN sys.tables pt ON pt.object_id = fk.parent_object_id JOIN sys.schemas ps ON ps.schema_id = pt.schema_id JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id JOIN sys.tables rt ON rt.object_id = fk.referenced_object_id JOIN sys.schemas rs ON rs.schema_id = rt.schema_id JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id ORDER BY ps.name, pt.name, fk.name, fkc.constraint_column_id`,
  indexes: `SELECT s.name AS schema_name, t.name AS table_name, i.name AS index_name, i.type_desc AS index_type, i.is_unique, i.is_primary_key, i.is_unique_constraint, i.is_disabled, ic.key_ordinal AS column_order, c.name AS column_name, ic.is_included_column, ic.is_descending_key, i.has_filter, i.filter_definition FROM sys.indexes i JOIN sys.tables t ON t.object_id = i.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id LEFT JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id LEFT JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id WHERE i.index_id > 0 AND t.is_ms_shipped = 0 ORDER BY s.name, t.name, i.name, ic.key_ordinal`,
  uniqueConstraints: `SELECT kc.name AS constraint_name, s.name AS schema_name, t.name AS table_name, c.name AS column_name, ic.key_ordinal AS key_order, i.type_desc AS index_type FROM sys.key_constraints kc JOIN sys.tables t ON t.object_id = kc.parent_object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.indexes i ON i.object_id = kc.parent_object_id AND i.index_id = kc.unique_index_id JOIN sys.index_columns ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id WHERE kc.type = 'UQ' ORDER BY s.name, t.name, kc.name, ic.key_ordinal`,
  checkConstraints: `SELECT cc.name AS constraint_name, s.name AS schema_name, t.name AS table_name, cc.definition, cc.is_disabled, cc.is_not_trusted FROM sys.check_constraints cc JOIN sys.tables t ON t.object_id = cc.parent_object_id JOIN sys.schemas s ON s.schema_id = t.schema_id ORDER BY s.name, t.name, cc.name`,
  defaultConstraints: `SELECT dc.name AS constraint_name, s.name AS schema_name, t.name AS table_name, c.name AS column_name, dc.definition FROM sys.default_constraints dc JOIN sys.tables t ON t.object_id = dc.parent_object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id ORDER BY s.name, t.name, c.column_id`,
  views: `SELECT s.name AS schema_name, v.name AS view_name, v.create_date, v.modify_date, sm.definition FROM sys.views v JOIN sys.schemas s ON s.schema_id = v.schema_id LEFT JOIN sys.sql_modules sm ON sm.object_id = v.object_id ORDER BY s.name, v.name`,
  storedProcedures: `SELECT s.name AS schema_name, p.name AS procedure_name, p.create_date, p.modify_date, sm.definition FROM sys.procedures p JOIN sys.schemas s ON s.schema_id = p.schema_id LEFT JOIN sys.sql_modules sm ON sm.object_id = p.object_id WHERE p.is_ms_shipped = 0 ORDER BY s.name, p.name`,
  functions: `SELECT s.name AS schema_name, o.name AS function_name, o.type_desc AS function_type, o.create_date, o.modify_date, sm.definition FROM sys.objects o JOIN sys.schemas s ON s.schema_id = o.schema_id LEFT JOIN sys.sql_modules sm ON sm.object_id = o.object_id WHERE o.type IN ('FN','FS','FT','IF','TF') AND o.is_ms_shipped = 0 ORDER BY s.name, o.name`,
  triggers: `SELECT s.name AS schema_name, t.name AS table_name, tr.name AS trigger_name, tr.type_desc AS trigger_type, tr.is_disabled, tr.is_instead_of_trigger, tr.create_date, tr.modify_date, sm.definition FROM sys.triggers tr JOIN sys.tables t ON t.object_id = tr.parent_id JOIN sys.schemas s ON s.schema_id = t.schema_id LEFT JOIN sys.sql_modules sm ON sm.object_id = tr.object_id WHERE tr.parent_class = 1 ORDER BY s.name, t.name, tr.name`,
  dependencies: `SELECT OBJECT_SCHEMA_NAME(d.referencing_id) AS referencing_schema, OBJECT_NAME(d.referencing_id) AS referencing_object, o.type_desc AS referencing_object_type, d.referenced_server_name, d.referenced_database_name, d.referenced_schema_name, d.referenced_entity_name, d.referenced_minor_name AS referenced_column, d.is_schema_bound_reference, d.is_caller_dependent, d.is_ambiguous FROM sys.sql_expression_dependencies d LEFT JOIN sys.objects o ON o.object_id = d.referencing_id ORDER BY referencing_schema, referencing_object, d.referenced_schema_name, d.referenced_entity_name`,
  identityColumns: `SELECT s.name AS schema_name, t.name AS table_name, c.name AS column_name, ic.seed_value, ic.increment_value, ic.last_value AS metadata_last_value, ty.name AS data_type, c.is_nullable FROM sys.identity_columns ic JOIN sys.tables t ON t.object_id = ic.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id JOIN sys.types ty ON ty.user_type_id = c.user_type_id ORDER BY s.name, t.name, c.column_id`,
  sequences: `SELECT s.name AS schema_name, seq.name AS sequence_name, ty.name AS data_type, seq.start_value, seq.increment, seq.minimum_value, seq.maximum_value, seq.current_value, seq.is_cycling, seq.is_exhausted, seq.cache_size FROM sys.sequences seq JOIN sys.schemas s ON s.schema_id = seq.schema_id JOIN sys.types ty ON ty.user_type_id = seq.user_type_id ORDER BY s.name, seq.name`,
  specialDataTypes: `SELECT s.name AS schema_name, t.name AS table_name, c.column_id, c.name AS column_name, ty.name AS data_type, c.max_length, c.precision, c.scale, c.is_nullable, c.collation_name, cc.definition AS computed_definition, dc.definition AS default_value FROM sys.columns c JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id JOIN sys.types ty ON ty.user_type_id = c.user_type_id LEFT JOIN sys.computed_columns cc ON cc.object_id = c.object_id AND cc.column_id = c.column_id LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id WHERE ty.name IN ('xml','text','ntext','image','sql_variant','varbinary','binary','geography','geometry','hierarchyid','timestamp','smallmoney') OR (ty.name IN ('varchar','nvarchar','char','nchar') AND c.max_length = -1) OR (ty.name IN ('numeric','decimal') AND c.precision > 18) ORDER BY s.name, t.name, c.column_id`,
  userDefinedTypes: `SELECT s.name AS schema_name, ty.name AS type_name, ty.is_user_defined, ty.is_assembly_type, ty.max_length, ty.precision, ty.scale, ty.collation_name FROM sys.types ty JOIN sys.schemas s ON s.schema_id = ty.schema_id WHERE ty.is_user_defined = 1 OR ty.is_assembly_type = 1 ORDER BY s.name, ty.name`,
  extendedProperties: `SELECT OBJECT_SCHEMA_NAME(ep.major_id) AS schema_name, OBJECT_NAME(ep.major_id) AS object_name, ep.minor_id, ep.name AS property_name, CONVERT(nvarchar(4000), ep.value) AS property_value FROM sys.extended_properties ep WHERE ep.class = 1 ORDER BY schema_name, object_name, ep.minor_id, ep.name`,
} as const

export type AegisMetadata = { database: { database_name: string; server_name: string | null; sql_server_version: string | null }; summary: Record<string, number>; [key: string]: unknown }

function getConfig(): sql.config {
  const required = ["SQLSERVER_HOST", "SQLSERVER_DATABASE", "SQLSERVER_USER", "SQLSERVER_PASSWORD"] as const
  for (const name of required) if (!process.env[name]) throw new Error(`${name} is not configured`)
  return { server: process.env.SQLSERVER_HOST!, port: Number(process.env.SQLSERVER_PORT || 1433), database: process.env.SQLSERVER_DATABASE!, user: process.env.SQLSERVER_USER!, password: process.env.SQLSERVER_PASSWORD!, options: { encrypt: process.env.SQLSERVER_ENCRYPT !== "false", trustServerCertificate: process.env.SQLSERVER_TRUST_SERVER_CERTIFICATE === "true" }, pool: { max: 2, min: 0, idleTimeoutMillis: 30000 }, connectionTimeout: 10000, requestTimeout: 120000 }
}

export async function readAegisMetadata(): Promise<AegisMetadata> {
  const pool = await sql.connect(getConfig())
  try {
    const result: Record<string, unknown> = {}
    for (const [section, query] of Object.entries(readOnlyQueries)) result[section] = (await pool.request().query(query)).recordset
    const db = (await pool.request().query(`SELECT DB_NAME() AS database_name, SERVERPROPERTY('ServerName') AS server_name, SERVERPROPERTY('ProductVersion') AS sql_server_version`)).recordset[0]
    result.database = db
    result.summary = { tableCount: (result.tables as unknown[]).length, columnCount: (result.columns as unknown[]).length, primaryKeyCount: (result.primaryKeys as unknown[]).length, foreignKeyCount: (result.foreignKeys as unknown[]).length, indexCount: (result.indexes as unknown[]).length, uniqueConstraintCount: (result.uniqueConstraints as unknown[]).length, checkConstraintCount: (result.checkConstraints as unknown[]).length, defaultConstraintCount: (result.defaultConstraints as unknown[]).length, viewCount: (result.views as unknown[]).length, storedProcedureCount: (result.storedProcedures as unknown[]).length, functionCount: (result.functions as unknown[]).length, triggerCount: (result.triggers as unknown[]).length, sequenceCount: (result.sequences as unknown[]).length }
    return result as AegisMetadata
  } finally { await pool.close() }
}

export function isReadOnlyMetadataQuery(query: string) { return /^\s*SELECT\b/i.test(query) }

export { readOnlyQueries }
