import { createHash } from "node:crypto"
import type { ExportPackage } from "@/lib/aegis-export-package"

type Row = Record<string, unknown>
type TargetSchema = { tables: Row[]; columns: Row[]; constraints: Row[]; indexes: Row[]; counts: Row[] }
const norm = (value: unknown) => String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, "")
const sourceTable = (row: Row) => String(row.table_name ?? row.table ?? row.name ?? "")
const sourceColumn = (row: Row) => String(row.column_name ?? row.column ?? row.name ?? "")
const tableData = (pkg: ExportPackage, table: string) => { const key = Object.keys(pkg.tableData).find((name) => norm(name).includes(norm(table))); return key ? pkg.tableData[key] : [] }
const values = (rows: Row[], key: string) => rows.map((row) => row[key]).filter((value) => value !== null && value !== undefined && value !== "")
const isDeleted = (row: Row) => Object.entries(row).some(([key, value]) => /^(is_?deleted|deleted|deleted_?flag)$/i.test(key) && (value === true || String(value) === "1"))
const status = (target: Row | undefined, sourceType: string) => target ? "SAFE_TO_MIGRATE" : sourceType ? "NEEDS_TARGET_SCHEMA" : "PRESERVE_IN_AUDIT_ONLY"
export function buildAuthoritativeMatrix(pkg: ExportPackage, target: TargetSchema, packageSha256: string) {
  const sourceTables = pkg.tables.map(sourceTable).filter(Boolean)
  const fieldMatrix: Row[] = []
  const approvalCounts = { SAFE_TO_MIGRATE: 0, NEEDS_TARGET_SCHEMA: 0, NEEDS_BUSINESS_DECISION: 0, PRESERVE_IN_AUDIT_ONLY: 0, BLOCKED: 0 }
  for (const table of sourceTables) {
    const rows = tableData(pkg, table)
    const metadata = pkg.columns.filter((row) => sourceTable(row).toLowerCase() === table.toLowerCase())
    const fields: Row[] = metadata.length ? metadata : [...new Set(rows.flatMap((row) => Object.keys(row)))].map((column) => ({ table_name: table, column_name: column }))
    for (const field of fields) {
      const column = sourceColumn(field); const sample = values(rows, column); const targetTable = target.tables.find((candidate) => norm(candidate.table_name) === norm(table)); const targetColumn = target.columns.find((candidate) => norm(candidate.table_name) === norm(table) && norm(candidate.column_name) === norm(column)); const sourceType = String(field.data_type ?? field.type ?? "NOT_AVAILABLE_FROM_EXPORT"); const sourceNullable = field.is_nullable ?? field.nullable ?? "NOT_AVAILABLE_FROM_EXPORT"; const targetType = targetColumn?.data_type ?? targetColumn?.udt_name ?? "NOT_AVAILABLE"; const pk = pkg.primaryKeys.filter((row) => sourceTable(row).toLowerCase() === table.toLowerCase() && norm(row.column_name) === norm(column)); const fk = pkg.foreignKeys.filter((row) => sourceTable(row).toLowerCase() === table.toLowerCase() && norm(row.source_column ?? row.column_name) === norm(column)); let fieldStatus = status(targetColumn, sourceType); let reason = targetColumn ? "Exact table and column name exists; type, nullability, semantics, and key compatibility require review." : "No exact operational target exists; preserve in audit until target schema is approved."; if (table.toLowerCase() === "tblhseinc" && /sev|severity/i.test(column)) { fieldStatus = "NEEDS_BUSINESS_DECISION"; reason = "Severity must not be converted without an approved value policy." } if (/password|token|secret/i.test(column)) { fieldStatus = "BLOCKED"; reason = "Sensitive source field is blocked from operational migration." } approvalCounts[fieldStatus as keyof typeof approvalCounts]++
      fieldMatrix.push({ source_table: table, source_column: column, source_type: sourceType, source_nullable: sourceNullable, source_row_count: rows.length, source_non_null_count: sample.length, source_null_count: rows.length - sample.length, source_distinct_count: new Set(sample.map(String)).size, source_example_values: sample.slice(0, 5), source_pk_fk: { primary_key: pk, foreign_key: fk }, target_table: targetTable?.table_schema && targetTable.table_name ? `${targetTable.table_schema}.${targetTable.table_name}` : "NOT_AVAILABLE", target_column: targetColumn?.column_name ?? "NOT_AVAILABLE", target_type: targetType, target_nullable: targetColumn?.is_nullable ?? "NOT_AVAILABLE_FROM_NEON", target_fk: targetColumn ? target.constraints.filter((constraint) => constraint.table_name === targetColumn.table_name && constraint.column_name === targetColumn.column_name) : [], transformation: "NONE — preserve source value", status: fieldStatus, reason, risk: targetColumn ? "Type/nullability/key semantic mismatch risk" : "No target schema; operational write blocked" })
    }
  }
  const lookupNames = ["Incident Type", "Severity", "Probability", "Hazard Category", "Activity Type", "Site", "Department", "Business Unit", "Work Area", "Breach/LSR", "Employee", "Client", "Injury Type", "Outcome", "Damage", "Currency", "Asset", "Vehicle", "Potential Severity"]
  const lookupMatrix = lookupNames.map((lookup) => ({ lookup, source_values: "NOT_AVAILABLE_FROM_EXPORT unless a dedicated lookup table is present", target_values: "NOT_AVAILABLE_FROM_NEON unless an exact lookup table is present", comparison: "NO_MATCH", action: "Do not create missing values", status: "NEEDS_BUSINESS_DECISION" }))
  const relationshipMatrix = pkg.foreignKeys.map((fk) => ({ source_table: sourceTable(fk), source_column: String(fk.source_column ?? fk.column_name ?? "NOT_AVAILABLE_FROM_EXPORT"), target_table: String(fk.target_table ?? fk.referenced_table ?? "NOT_AVAILABLE_FROM_EXPORT"), target_column: String(fk.target_column ?? fk.referenced_column ?? "NOT_AVAILABLE_FROM_EXPORT"), parent_row_count: "CALCULATED_FROM_EXPORT_IF_AVAILABLE", child_row_count: "CALCULATED_FROM_EXPORT_IF_AVAILABLE", orphan_child_rows: "NOT_AVAILABLE_FROM_EXPORT", duplicate_relationship_keys: "NOT_AVAILABLE_FROM_EXPORT", status: "NEEDS_TARGET_SCHEMA" }))
  const report = { report_version: "authoritative-migration-matrix-v1", generated_at: new Date().toISOString(), source_package_sha256: packageSha256, source_table_count: sourceTables.length, source_row_count: pkg.rowCounts.reduce((sum, row) => sum + Number(row.row_count ?? row.count ?? 0), 0), target_table_count: target.tables.length, target_row_count: target.counts.reduce((sum, row) => sum + Number(row.row_count ?? 0), 0), metadata_availability: { schema_metadata: pkg.tables.length ? "YES" : "NOT_AVAILABLE_FROM_EXPORT", column_types: pkg.columns.some((row) => row.data_type || row.type) ? "YES" : "NOT_AVAILABLE_FROM_EXPORT", nullable_metadata: pkg.columns.some((row) => row.is_nullable || row.nullable) ? "YES" : "NOT_AVAILABLE_FROM_EXPORT", pk_metadata: pkg.primaryKeys.length ? "YES" : "NOT_AVAILABLE_FROM_EXPORT", fk_metadata: pkg.foreignKeys.length ? "YES" : "NOT_AVAILABLE_FROM_EXPORT" }, field_matrix: fieldMatrix, lookup_matrix: lookupMatrix, relationship_matrix: relationshipMatrix, approval_counts: approvalCounts, existing_neon_incident_protection: { current_row_count: "READ_FROM_NEON", updates: 0, deletes: 0, writes: 0 }, unresolved_items: ["Exact target schema for requested operational tables", "Lookup value equivalence", "Deleted-row policy", "Relationship orphan verification"] }
  return { ...report, artifact_sha256: createHash("sha256").update(JSON.stringify(report)).digest("hex") }
}
export type AuthoritativeMatrix = ReturnType<typeof buildAuthoritativeMatrix>
