import type { ExportPackage } from "@/lib/aegis-export-package"
import type { NormalizedMetadata } from "@/lib/migration-analysis"
import { buildFieldMappingProposal } from "@/lib/aegis-field-mapping"

const requiredTables = [
  "tblHSEINC", "tblInvestigation", "tblAssetLoss", "tblAutomotiveLoss", "tblEnvironmentalLoss", "tblPersonalLoss", "tblHSESafetyAlert", "tblImmediateCauseSA", "tblImmediateCauseSC", "tblInvestigation_Has_Papers", "tblInvestigation_Has_Parts", "tblInvestigation_has_PeopleAndPositions", "tblInvestigation_Has_Processes", "tblJobFactor", "tblManagementFactor", "tblPersonalFactor",
]
const targetProposals: Record<string, string> = {
  tblHSEINC: "incident (new additive target required)", tblInvestigation: "investigation (new additive target required)", tblAssetLoss: "loss_event / asset_loss (review required)", tblAutomotiveLoss: "loss_event / automotive_loss (review required)", tblEnvironmentalLoss: "loss_event / environmental_loss (review required)", tblPersonalLoss: "loss_event / personal_loss (review required)", tblHSESafetyAlert: "safety_alert (new additive target required)", tblImmediateCauseSA: "incident_cause (new additive target required)", tblImmediateCauseSC: "incident_cause (new additive target required)", tblInvestigation_Has_Papers: "investigation_document (new additive target required)", tblInvestigation_Has_Parts: "investigation_part (new additive target required)", tblInvestigation_has_PeopleAndPositions: "investigation_person_position (new additive target required)", tblInvestigation_Has_Processes: "investigation_process (new additive target required)", tblJobFactor: "job_factor (new additive target required)", tblManagementFactor: "management_factor (new additive target required)", tblPersonalFactor: "personal_factor (new additive target required)",
}
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "")
const rowTable = (row: Record<string, unknown>) => String(row.table_name ?? row.table ?? row.name ?? "")
const rowCount = (pkg: ExportPackage, table: string) => { const match = pkg.tables.find((row) => rowTable(row).toLowerCase() === table.toLowerCase()); if (match) return Number(match.row_count ?? match.rowCount ?? match.count ?? match.records ?? 0); const key = Object.keys(pkg.tableData).find((name) => normalize(name).includes(normalize(table))); return key ? pkg.tableData[key].length : 0 }
const rowsFor = (pkg: ExportPackage, table: string) => { const key = Object.keys(pkg.tableData).find((name) => normalize(name).includes(normalize(table))); return key ? pkg.tableData[key] : [] }
const isDeleted = (row: Record<string, unknown>) => ["deleted", "isdeleted", "deletedflag", "status"].some((key) => { const value = Object.entries(row).find(([name]) => normalize(name) === key)?.[1]; return value === true || String(value ?? "").toLowerCase() === "deleted" || String(value ?? "") === "1" })
const fieldNames = (pkg: ExportPackage, table: string) => pkg.columns.filter((row) => String(row.table_name ?? row.table ?? "").toLowerCase() === table.toLowerCase()).map((row) => String(row.column_name ?? row.column ?? "")).filter(Boolean)
export function buildMigrationPreview(pkg: ExportPackage, metadata: NormalizedMetadata, analysis: Record<string, unknown>) {
  const matrix = Array.isArray(analysis.matrix) ? analysis.matrix as Array<Record<string, unknown>> : []
  const rows = requiredTables.map((table) => {
    const sourceRows = rowsFor(pkg, table); const sourceCount = Math.max(rowCount(pkg, table), sourceRows.length); const deleted = sourceRows.filter(isDeleted).length; const matrixRow = matrix.find((item) => String(item.sourceTable ?? "").toLowerCase().endsWith(`.${table.toLowerCase()}`)); const mapped = matrixRow && matrixRow.targetTable !== "NOT AVAILABLE"; const mappingIssues = fieldNames(pkg, table).filter((field) => !String(matrixRow?.targetTable ?? "").includes("public.")).length;
    return { aegisSourceTable: table, sourceRowCount: sourceCount, targetNeonTable: targetProposals[table] ?? "NOT MAPPED", targetRowCount: "NOT AVAILABLE — no approved operational mapping", rowsEligibleForMigration: 0, rowsAlreadyMigrated: 0, rowsWouldBeInserted: 0, rowsWouldBeUpdated: 0, rowsSkipped: sourceCount, deletedHistoricalRows: deleted, duplicateRecords: "NOT DETERMINED — no approved target key", mappingIssues: mappingIssues || "NOT AVAILABLE", missingRelationships: "NOT DETERMINED — relationship mapping requires review", unmappedFields: fieldNames(pkg, table).length || "NOT AVAILABLE", proposedTargetColumns: fieldNames(pkg, table), proposedTargetTable: targetProposals[table] ?? "REVIEW REQUIRED", decision: mapped ? "REVIEW REQUIRED — no operational write" : "UNMAPPED — no operational write", note: table === "tblHSEINC" ? "Preserve all source incidents, including deleted history; preserve Event_Id, Event_Number, original severity, HighPotential, HSE_Recordable, and all source fields." : "Source rows remain in the validated audit import only." }
  })
  const incidentRows = rowsFor(pkg, "tblHSEINC"); const incidentStatus = { total: incidentRows.length, active: incidentRows.filter((row) => !isDeleted(row)).length, deleted: incidentRows.filter(isDeleted).length, severityPreserved: incidentRows.every((row) => Object.keys(row).some((key) => /severity/i.test(key))) }
  const lookupTables = pkg.tables.map(rowTable).filter((name) => name && !requiredTables.some((required) => required.toLowerCase() === name.toLowerCase())).map((table) => ({ aegisSourceTable: table, classification: "LOOKUP_OR_REFERENCE_REVIEW_REQUIRED", sourceRowCount: rowCount(pkg, table), targetNeonTable: "NOT MAPPED", rowsWouldBeInserted: 0, rowsWouldBeUpdated: 0, rowsSkipped: rowCount(pkg, table), note: "Included for reconciliation; no guessed lookup mapping." }))
  return { requiredTables: rows, lookupTables, incidentRules: { ...incidentStatus, deletedRemainHistorical: true, severityRemapping: "NOT PERFORMED", operationalWrites: 0 }, totals: { sourceRows: rows.reduce((sum, row) => sum + row.sourceRowCount, 0), eligible: 0, alreadyMigrated: 0, wouldInsert: 0, wouldUpdate: 0, skipped: rows.reduce((sum, row) => sum + row.rowsSkipped, 0) }, mappingProposal: buildFieldMappingProposal(pkg, metadata), readOnly: true }
}
export { requiredTables }
