import * as XLSX from "xlsx"

export type MetadataRow = Record<string, unknown>
export type NormalizedTable = { schema: string; name: string; rowCount?: number; columns: MetadataRow[]; primaryKeys: MetadataRow[]; foreignKeys: MetadataRow[]; indexes: MetadataRow[]; uniques: MetadataRow[]; checks: MetadataRow[]; defaults: MetadataRow[] }
export type NormalizedMetadata = { source: "aegis" | "neon"; database?: string; tables: NormalizedTable[]; columns: MetadataRow[]; primaryKeys: MetadataRow[]; foreignKeys: MetadataRow[]; indexes: MetadataRow[]; uniques: MetadataRow[]; checks: MetadataRow[]; defaults: MetadataRow[]; views: MetadataRow[]; procedures: MetadataRow[]; functions: MetadataRow[]; triggers: MetadataRow[]; dependencies: MetadataRow[]; identities: MetadataRow[]; sequences: MetadataRow[]; dataTypes: MetadataRow[]; extendedProperties: MetadataRow[]; summary: Record<string, unknown>; available: Record<string, boolean>; protectedTables: string[] }

const aliases: Record<string, string[]> = {
  database: ["database information", "database"], tables: ["tables", "all tables", "table", "table inventory"], columns: ["columns", "all columns", "column"], primaryKeys: ["primary keys", "primary key", "pk"], foreignKeys: ["foreign keys", "foreign key", "fk"], indexes: ["indexes", "index"], uniques: ["unique constraints", "unique constraint", "unique"], checks: ["check constraints", "check constraint"], defaults: ["default constraints", "default constraint"], views: ["views", "view"], procedures: ["stored procedures", "procedures", "procedure"], functions: ["functions", "function"], triggers: ["triggers", "trigger"], dependencies: ["object dependencies", "dependencies", "dependency"], identities: ["identity columns", "identity column", "identity"], sequences: ["sequences", "sequence"], dataTypes: ["special and unusual data types", "data types", "data type", "unusual data types"], extendedProperties: ["extended properties", "extended property"], summary: ["metadata summary", "summary"]
}
const key = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/[\s_-]+/g, " ")
const sectionKey = (value: unknown) => Object.entries(aliases).find(([, names]) => names.some((name) => key(value) === name || key(value).includes(name)))?.[0]
const value = (row: MetadataRow, names: string[]) => Object.entries(row).find(([name]) => names.some((needle) => key(name) === needle || key(name).includes(needle)))?.[1]
export const text = (row: MetadataRow, names: string[]) => String(value(row, names) ?? "").trim()
const tableRef = (row: MetadataRow) => ({ schema: text(row, ["schema", "schema name", "table schema"]) || "dbo", name: text(row, ["table", "table name", "parent table", "object name"]) })
export const requiredSections = ["database", "tables", "columns", "primaryKeys", "foreignKeys", "indexes", "uniques", "checks", "defaults", "views", "procedures", "functions", "triggers", "dependencies", "identities", "sequences", "dataTypes", "extendedProperties", "summary"] as const
function sectionRows(raw: Record<string, unknown>, name: string) { const direct = Object.entries(raw).find(([k]) => sectionKey(k) === name)?.[1]; return Array.isArray(direct) ? direct as MetadataRow[] : direct && typeof direct === "object" ? [direct as MetadataRow] : [] }
export function parseWorkbook(buffer: Buffer, extension: string) { if (extension === ".json" || extension === ".txt") { try { const parsed = JSON.parse(buffer.toString("utf8")); return parsed && typeof parsed === "object" ? parsed as Record<string, unknown> : { tables: parsed } } catch { return parseDelimited(buffer.toString("utf8")) } } const workbook = XLSX.read(buffer, { type: "buffer" }); return Object.fromEntries(workbook.SheetNames.map((sheet) => [sheet, XLSX.utils.sheet_to_json(workbook.Sheets[sheet], { defval: null })])) as Record<string, unknown> }
function parseDelimited(input: string) { const lines = input.split(/\r?\n/).filter(Boolean); const delimiter = lines[0]?.includes("\t") ? "\t" : ","; const headers = (lines[0] ?? "").split(delimiter).map((x) => x.trim()); return { tables: lines.slice(1).map((line) => Object.fromEntries(line.split(delimiter).map((cell, i) => [headers[i] ?? `column_${i}`, cell.trim()]))) } }
export function normalizeMetadata(raw: Record<string, unknown>, source: "aegis" | "neon" = "aegis"): NormalizedMetadata {
  const all: Record<string, MetadataRow[]> = Object.fromEntries(requiredSections.map((name) => [name, sectionRows(raw, name)])); const tables = new Map<string, NormalizedTable>();
  for (const row of all.tables) { const ref = tableRef(row); if (ref.name) tables.set(`${ref.schema}.${ref.name}`, { ...ref, rowCount: Number(value(row, ["count", "records", "record count", "row count"])) || undefined, columns: [], primaryKeys: [], foreignKeys: [], indexes: [], uniques: [], checks: [], defaults: [] }) }
  const ensure = (row: MetadataRow) => { const ref = tableRef(row); if (!ref.name) return; const id = `${ref.schema}.${ref.name}`; if (!tables.has(id)) tables.set(id, { ...ref, columns: [], primaryKeys: [], foreignKeys: [], indexes: [], uniques: [], checks: [], defaults: [] }); return tables.get(id) }
  for (const row of all.columns) ensure(row)?.columns.push(row)
  for (const [field, name] of [["primaryKeys", "primaryKeys"], ["foreignKeys", "foreignKeys"], ["indexes", "indexes"], ["uniques", "uniques"], ["checks", "checks"], ["defaults", "defaults"]] as const) for (const row of all[name]) { const target = ensure(row); if (target) target[field].push(row) }
  return { source, database: text(all.database[0] ?? {}, ["database", "database name"]), tables: [...tables.values()], columns: all.columns, primaryKeys: all.primaryKeys, foreignKeys: all.foreignKeys, indexes: all.indexes, uniques: all.uniques, checks: all.checks, defaults: all.defaults, views: all.views, procedures: all.procedures, functions: all.functions, triggers: all.triggers, dependencies: all.dependencies, identities: all.identities, sequences: all.sequences, dataTypes: all.dataTypes, extendedProperties: all.extendedProperties, summary: all.summary[0] ?? {}, available: Object.fromEntries(requiredSections.map((name) => [name, all[name].length > 0])), protectedTables: [] }
}
const protectedNames = ["neon_auth.user", "neon_auth.account", "neon_auth.session", "neon_auth.verification", "neon_auth.organization", "neon_auth.member", "neon_auth.invitation", "neon_auth.jwks", "neon_auth.project_config", "public.password_reset_token", "public.password_reset_otp"]
export function compareMetadata(aegis: NormalizedMetadata, neon: NormalizedMetadata) {
  const neonByName = new Map(neon.tables.map((table) => [table.name.toLowerCase(), table]));
  const columnsOf = (table?: NormalizedTable) => new Set((table?.columns ?? []).map((row) => text(row, ["column", "column name"]).toLowerCase()).filter(Boolean));
  const similarity = (source: NormalizedTable, target: NormalizedTable) => { const a = columnsOf(source); const b = columnsOf(target); const overlap = [...a].filter((column) => b.has(column)).length; return { overlap, confidence: a.size ? Math.round((overlap / a.size) * 100) : 0 } };
  const matrix = aegis.tables.map((source) => {
    const exact = neonByName.get(source.name.toLowerCase());
    const candidates = neon.tables.map((target) => ({ target, ...similarity(source, target) })).filter((candidate) => candidate.overlap > 0).sort((a, b) => b.confidence - a.confidence || b.overlap - a.overlap);
    const best = exact ?? candidates[0]?.target;
    const score = best ? similarity(source, best) : { overlap: 0, confidence: 0 };
    const possible = !exact && score.confidence >= 40;
    const matchType = exact ? score.confidence === 100 ? "EXACT_NAME_MATCH" : score.confidence >= 60 ? "STRUCTURAL_MATCH" : "PARTIAL_NAME_MATCH" : possible ? "POSSIBLE_MATCH_REQUIRES_REVIEW" : "NO_MATCH";
    return { sourceTable: `${source.schema}.${source.name}`, targetTable: best ? `${best.schema}.${best.name}` : "NOT AVAILABLE", matchType, confidence: score.confidence, sharedColumns: score.overlap, sourceRecords: source.rowCount ?? "NOT AVAILABLE", targetRecords: best?.rowCount ?? "NOT AVAILABLE", recommendedAction: exact ? "REVIEW_REQUIRED" : possible ? "POSSIBLE_MATCH_REQUIRES_REVIEW" : "LEGACY_ONLY", reason: exact ? `${score.overlap}/${columnsOf(source).size || "unknown"} column names overlap; types, nullability, keys, and semantics still require review.` : possible ? `Possible match based on ${score.overlap} shared column names; names differ, so equivalence is not confirmed.` : "No credible target table was found from metadata." };
  });
  const matchedTargets = new Set(matrix.map((row) => row.targetTable).filter((name) => name !== "NOT AVAILABLE"));
  const extraNeonTables = neon.tables.filter((table) => !matchedTargets.has(`${table.schema}.${table.name}`)).map((table) => `${table.schema}.${table.name}`);
  const columnMapping = aegis.tables.flatMap((source) => { const targetName = matrix.find((row) => row.sourceTable === `${source.schema}.${source.name}`)?.targetTable; const target = neon.tables.find((table) => `${table.schema}.${table.name}` === targetName); return source.columns.map((row) => { const name = text(row, ["column", "column name"]); const targetColumn = target?.columns.find((c) => text(c, ["column", "column name"]).toLowerCase() === name.toLowerCase()); return { sourceTable: `${source.schema}.${source.name}`, sourceColumn: name, sourceType: text(row, ["type", "data type"]), targetTable: targetName ?? "NOT AVAILABLE", targetColumn: targetColumn ? name : "NOT AVAILABLE", targetType: targetColumn ? text(targetColumn, ["type", "data type"]) : "NOT AVAILABLE", mappingType: targetColumn ? "NAME_MATCH_REQUIRES_TYPE_REVIEW" : "NO_CONFIRMED_TARGET", confidence: targetColumn ? 100 : 0, reason: targetColumn ? "Column name match only; validate type, nullability, default, and semantics." : "No confirmed target column." } }); });
  const protectedTables = neon.tables.filter((table) => protectedNames.includes(`${table.schema}.${table.name}`.toLowerCase()) || table.schema === "neon_auth").map((table) => `${table.schema}.${table.name}`); const fkGraph = aegis.foreignKeys.map((fk) => ({ parentTable: text(fk, ["parent table", "table"]), parentColumn: text(fk, ["parent column", "column"]), referencedTable: text(fk, ["referenced table"]), referencedColumn: text(fk, ["referenced column"]), constraint: text(fk, ["constraint", "constraint name"]), source: "Aegis metadata" }));
  return { matrix, extraNeonTables, columnMapping, protectedTables, fkGraph, idAnalysis: aegis.tables.map((table) => ({ table: `${table.schema}.${table.name}`, sourcePkType: text(table.primaryKeys[0] ?? {}, ["type", "data type", "sql server data type"]) || "NOT AVAILABLE", targetPkType: "NOT AVAILABLE", sameType: "NOT DETERMINED", collisionRisk: "NOT DETERMINED WITHOUT DATA", mappingRequired: "REVIEW REQUIRED" })), duplicateAnalysis: [{ status: "NOT AVAILABLE", reason: "No row-level source and target exports were provided." }], orphanAnalysis: [{ status: "NOT AVAILABLE", reason: "No row-level FK checks were executed." }], risks: [{ severity: "CRITICAL", title: "No migration is permitted in this stage", detail: "The interface exposes comparison and reporting only." }, { severity: "HIGH", title: "Possible matches require review", detail: "Column overlap is a heuristic, not proof of equivalence." }, { severity: "HIGH", title: "Row-level comparison is unavailable", detail: "Metadata cannot prove missing, changed, duplicate, or orphaned records." }] }
}
export function toCsv(rows: unknown[]) { if (!rows.length) return ""; const objects = rows as Record<string, unknown>[]; const headers = [...new Set(objects.flatMap((row) => Object.keys(row)))]; return [headers.join(","), ...objects.map((row) => headers.map((h) => JSON.stringify(row[h] ?? "")).join(","))].join("\n") }
export { protectedNames }
