import * as XLSX from "xlsx"

export type MetadataRow = Record<string, unknown>
export type NormalizedTable = { schema: string; name: string; rowCount?: number; columns: MetadataRow[]; primaryKeys: MetadataRow[]; foreignKeys: MetadataRow[]; indexes: MetadataRow[]; uniques: MetadataRow[]; checks: MetadataRow[]; defaults: MetadataRow[] }
export type NormalizedMetadata = { source: "aegis" | "neon"; database?: string; tables: NormalizedTable[]; views: MetadataRow[]; procedures: MetadataRow[]; functions: MetadataRow[]; triggers: MetadataRow[]; dependencies: MetadataRow[]; identities: MetadataRow[]; sequences: MetadataRow[]; summary: Record<string, unknown>; protectedTables: string[] }

const aliases: Record<string, string[]> = {
  tables: ["tables", "all tables", "table", "table inventory"], columns: ["columns", "all columns", "column"], primaryKeys: ["primary keys", "primary key", "pk"], foreignKeys: ["foreign keys", "foreign key", "fk"], indexes: ["indexes", "index"], uniques: ["unique constraints", "unique constraint", "unique"], checks: ["check constraints", "check constraint"], defaults: ["default constraints", "default constraint"], views: ["views", "view"], procedures: ["stored procedures", "procedures", "procedure"], functions: ["functions", "function"], triggers: ["triggers", "trigger"], dependencies: ["object dependencies", "dependencies", "dependency"], identities: ["identity columns", "identity column", "identity"], sequences: ["sequences", "sequence"], summary: ["metadata summary", "summary"], database: ["database information", "database"] }
const key = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/[\s_-]+/g, " ")
const sectionKey = (value: unknown) => Object.entries(aliases).find(([, names]) => names.some((name) => key(value) === name || key(value).includes(name)))?.[0]
const value = (row: MetadataRow, names: string[]) => { const found = Object.entries(row).find(([name]) => names.some((needle) => key(name) === needle || key(name).includes(needle))); return found?.[1] }
const text = (row: MetadataRow, names: string[]) => String(value(row, names) ?? "").trim()
const tableRef = (row: MetadataRow) => ({ schema: text(row, ["schema", "schema name", "table schema"]) || "dbo", name: text(row, ["table", "table name", "parent table", "object name"]) })

export function rowsFromText(input: string) {
  try { const parsed = JSON.parse(input); if (Array.isArray(parsed)) return { tables: parsed } as Record<string, MetadataRow[]>; return parsed as Record<string, MetadataRow[]> } catch { return parseDelimited(input) }
}
function parseDelimited(input: string) { const lines = input.split(/\r?\n/).filter(Boolean); const delimiter = lines[0]?.includes("\t") ? "\t" : ","; const headers = lines[0]?.split(delimiter).map((x) => x.trim()) ?? []; return { tables: lines.slice(1).map((line) => Object.fromEntries(line.split(delimiter).map((cell, i) => [headers[i] ?? `column_${i}`, cell.trim()]))) } }
function sectionRows(raw: Record<string, unknown>, name: string) { const direct = Object.entries(raw).find(([k]) => sectionKey(k) === name)?.[1]; if (Array.isArray(direct)) return direct as MetadataRow[]; if (direct && typeof direct === "object") return [direct as MetadataRow]; return [] }

export function normalizeMetadata(raw: Record<string, unknown>, source: "aegis" | "neon" = "aegis"): NormalizedMetadata {
  const tablesRows = sectionRows(raw, "tables"); const columns = sectionRows(raw, "columns"); const tables = new Map<string, NormalizedTable>()
  for (const row of tablesRows) { const ref = tableRef(row); if (!ref.name) continue; tables.set(`${ref.schema}.${ref.name}`, { ...ref, rowCount: Number(value(row, ["count", "records", "record count", "row count"])) || undefined, columns: [], primaryKeys: [], foreignKeys: [], indexes: [], uniques: [], checks: [], defaults: [] }) }
  const ensure = (row: MetadataRow) => { const ref = tableRef(row); if (!ref.name) return undefined; const id = `${ref.schema}.${ref.name}`; if (!tables.has(id)) tables.set(id, { ...ref, columns: [], primaryKeys: [], foreignKeys: [], indexes: [], uniques: [], checks: [], defaults: [] }); return tables.get(id) }
  for (const row of columns) { const target = ensure(row); if (target) target.columns.push(row) }
  const map: Array<[keyof NormalizedTable, string]> = [["primaryKeys", "primaryKeys"], ["foreignKeys", "foreignKeys"], ["indexes", "indexes"], ["uniques", "uniques"], ["checks", "checks"], ["defaults", "defaults"]]
  for (const [field, name] of map) for (const row of sectionRows(raw, name)) { const target = ensure(row); if (target) (target[field] as MetadataRow[]).push(row) }
  return { source, database: text(sectionRows(raw, "database")[0] ?? {}, ["database", "database name"]), tables: [...tables.values()], views: sectionRows(raw, "views"), procedures: sectionRows(raw, "procedures"), functions: sectionRows(raw, "functions"), triggers: sectionRows(raw, "triggers"), dependencies: sectionRows(raw, "dependencies"), identities: sectionRows(raw, "identities"), sequences: sectionRows(raw, "sequences"), summary: sectionRows(raw, "summary")[0] ?? {}, protectedTables: [] }
}

const protectedNames = ["neon_auth.user", "neon_auth.account", "neon_auth.session", "neon_auth.verification", "neon_auth.organization", "neon_auth.member", "neon_auth.invitation", "neon_auth.jwks", "neon_auth.project_config"]
export function compareMetadata(aegis: NormalizedMetadata, neon: NormalizedMetadata) {
  const neonByName = new Map(neon.tables.map((table) => [table.name.toLowerCase(), table])); const matrix = aegis.tables.map((source) => { const target = neonByName.get(source.name.toLowerCase()); const sourceCols = new Set(source.columns.map((r) => text(r, ["column", "column name"]).toLowerCase())); const targetCols = new Set((target?.columns ?? []).map((r) => text(r, ["column", "column name"]).toLowerCase())); const overlap = [...sourceCols].filter((x) => targetCols.has(x)).length; const confidence = target && sourceCols.size ? Math.round((overlap / sourceCols.size) * 100) : 0; const match = !target ? "NO_MATCH" : confidence === 100 ? "EXACT_MATCH" : confidence >= 60 ? "STRUCTURAL_MATCH" : "PARTIAL_MATCH"; return { aegisTable: `${source.schema}.${source.name}`, neonTable: target ? `public.${target.name}` : "", match, confidence, action: target ? "REVIEW_REQUIRED" : "LEGACY_ONLY", reason: target ? `${overlap}/${sourceCols.size} column names overlap; constraints and business meaning require review.` : "No target table with the same name was found." } })
  const columnMapping = aegis.tables.flatMap((source) => { const target = neonByName.get(source.name.toLowerCase()); return source.columns.map((row) => { const name = text(row, ["column", "column name"]); const neonColumn = target?.columns.find((c) => text(c, ["column", "column name"]).toLowerCase() === name.toLowerCase()); return { aegisTable: source.name, aegisColumn: name, aegisType: text(row, ["type", "data type"]), neonTable: target?.name ?? "", neonColumn: neonColumn ? name : "", neonType: neonColumn ? text(neonColumn, ["type", "data type"]) : "", mapping: neonColumn ? "EXACT" : "NO_TARGET", confidence: neonColumn ? 100 : 0, notes: neonColumn ? "Name match only; validate type and semantics." : "No confirmed target column." } }) })
  const protectedTables = neon.tables.filter((table) => protectedNames.includes(`${table.schema}.${table.name}`.toLowerCase()) || table.schema === "neon_auth").map((table) => `${table.schema}.${table.name}`)
  return { matrix, columnMapping, protectedTables, fkGraph: aegis.tables.flatMap((t) => t.foreignKeys.map((fk) => ({ parentTable: text(fk, ["referenced table", "parent table"]), childTable: `${t.schema}.${t.name}`, fk: text(fk, ["constraint", "constraint name"]), columns: text(fk, ["column", "parent column"]), dependencyLevel: 0 }))), risks: [{ severity: "CRITICAL", title: "Read-only analysis gate", detail: "No migration operation is exposed by this analysis page." }, { severity: "HIGH", title: "Unconfirmed mappings", detail: "Name overlap is not treated as proof of equivalence; ambiguous mappings remain REVIEW_REQUIRED." }] }
}

export function parseWorkbook(buffer: Buffer, extension: string) { if (extension === ".json" || extension === ".txt") return rowsFromText(buffer.toString("utf8")); const workbook = XLSX.read(buffer, { type: "buffer" }); const output: Record<string, MetadataRow[]> = {}; for (const sheet of workbook.SheetNames) output[sheet] = XLSX.utils.sheet_to_json(workbook.Sheets[sheet], { defval: null }) as MetadataRow[]; return output }
export function toCsv(rows: unknown[]) { if (!rows.length) return ""; const objects = rows as Record<string, unknown>[]; const headers = [...new Set(objects.flatMap((row) => Object.keys(row)))]; return [headers.join(","), ...objects.map((row) => headers.map((h) => JSON.stringify(row[h] ?? "")).join(","))].join("\n") }
export { protectedNames }
