export type ObservationType = "Safe" | "Unsafe" | "At Risk"
export type Priority = "High" | "Medium" | "Low"
export type ObservationStatus = "Open" | "In Progress" | "Closed" | "Overdue" | "NoA" | "Approval Pending"

export interface ActionItem {
  id: string
  type: string
  action: string
  actionParty: string
  approver: string
  priority: Priority
  raisedDate: string
  targetDate: string
  status: ObservationStatus
  attachments: string[]
}

export interface Observation {
  id: string
  number: string
  date: string
  businessUnit: string
  observer: string
  observerEmail: string
  position: string
  location: string
  nearMiss: boolean
  draft: boolean
  description: string
  observationType: ObservationType
  category: string
  attachments: string[]
  correctiveActions: string
  actionItems: ActionItem[]
  status: ObservationStatus
  createdBy: string
  createdAt: string
  shared: boolean
}

export const observationCategories = [
  "PPE Compliance",
  "Housekeeping",
  "Manual Handling",
  "Equipment Safety",
  "Chemical Handling",
  "Fire Safety",
  "Electrical Safety",
  "Working at Height",
  "Confined Space",
  "Line of Fire",
  "Road Safety",
  "Lifting Operations",
  "Permit to Work",
  "Emergency Preparedness",
  "Environmental",
  "Procedure Compliance",
  "Communication",
  "Supervision",
  "Training",
  "General Safety",
]

export const positions = [
  "HSE",
  "Field Engineer",
  "Field Engineer (Trainee)",
  "Wireline Operator",
  "Operator Slickline",
  "Operations supervisor",
  "Foreman",
  "Base Manager",
  "Dirrectional Driller",
  "MWD/LWD Engineer",
  "OTHERS",
]

export const locations = [
  "Workshop/Base",
  "Well Site-Standalone",
  "Well Site-Rig",
  "Camp",
  "Store",
  "Daleel Site",
  "Office",
  "Road/Transport",
]

export const actionItemTypes = [
  "Corrective Action",
  "Preventive Action",
  "Training Required",
  "Equipment Repair",
  "Procedure Update",
  "Investigation",
  "Other",
]

// Real observations data from HSE system
export const observations: Observation[] = [
  {
    id: "1",
    number: "OBS-2024-0000001",
    date: "2024-08-04",
    businessUnit: "XOM Oman",
    observer: "Arwa Nasser AL-Habsi",
    observerEmail: "ahabsi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Wrong storage for grease seal oil. The drums were removed from the old warehouse and placed in the outdoor courtyard because there was no designated place to store oils drums. HAZARDS - The drums are in an outdoor courtyard under the high heat of the sun and it is a flammable material.",
    observationType: "Unsafe",
    category: "Chemical Handling",
    attachments: [],
    correctiveActions: "Transporting the grease seal oil to the empty area near the waste oil area, placing an umbrella to avoid exposure of the oils to sunlight and make sure to place iron sheets under the drums to prevent any leakage from reaching the ground",
    actionItems: [],
    status: "Closed",
    createdBy: "Arwa Nasser AL-Habsi(L-XOM-0049)",
    createdAt: "2024-08-04T17:00:51Z",
    shared: false,
  },
  {
    id: "2",
    number: "OBS-2024-0000002",
    date: "2024-08-05",
    businessUnit: "XOM Oman",
    observer: "Arwa Nasser AL-Habsi",
    observerEmail: "ahabsi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "The file containing the daily inspection of the forklift is completely corrupted",
    observationType: "Unsafe",
    category: "Equipment Safety",
    attachments: [],
    correctiveActions: "Change the entire file and allocate a suitable place to display the file, such as waterproof box",
    actionItems: [],
    status: "Closed",
    createdBy: "Arwa Nasser AL-Habsi(L-XOM-0049)",
    createdAt: "2024-08-05T13:50:26Z",
    shared: false,
  },
  {
    id: "3",
    number: "OBS-2024-0000003",
    date: "2024-08-19",
    businessUnit: "XOM Oman",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: true,
    draft: false,
    description: "Observed Florence light using instead of LED which may cause fire risk in work place",
    observationType: "Unsafe",
    category: "Fire Safety",
    attachments: [],
    correctiveActions: "Florence light must be change into LED light",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2024-08-19T08:41:27Z",
    shared: false,
  },
  {
    id: "4",
    number: "OBS-2024-0000004",
    date: "2024-08-25",
    businessUnit: "XOM Oman",
    observer: "Arwa Nasser AL-Habsi",
    observerEmail: "ahabsi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "The warning (flammable solid Lithium Batteries) sign at the entrance of lithium batteries room is completely damaged",
    observationType: "Unsafe",
    category: "Fire Safety",
    attachments: [],
    correctiveActions: "Ordering a new sign board",
    actionItems: [],
    status: "NoA",
    createdBy: "Arwa Nasser AL-Habsi(L-XOM-0049)",
    createdAt: "2024-08-25T11:56:14Z",
    shared: false,
  },
  {
    id: "5",
    number: "OBS-2024-0000007",
    date: "2024-08-20",
    businessUnit: "XOM Oman",
    observer: "Ishaq Ali Al Afeefi",
    observerEmail: "iaafeefi@xomoman.com",
    position: "Foreman",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "A stand of spooler not secured with safety pin for BAZ-8",
    observationType: "Unsafe",
    category: "Equipment Safety",
    attachments: [],
    correctiveActions: "I drill hole into stand to make pin",
    actionItems: [],
    status: "NoA",
    createdBy: "Ahmed Badar Al Jabri(L-HIR-0114)",
    createdAt: "2024-09-05T14:24:35Z",
    shared: false,
  },
  {
    id: "6",
    number: "OBS-2024-0000008",
    date: "2024-10-16",
    businessUnit: "XOM Well Maintenance",
    observer: "Saif Said Nasser Al Rashdi",
    observerEmail: "srashdi@xomoman.com",
    position: "Base Manager",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Welder working without a permit",
    observationType: "Unsafe",
    category: "Permit to Work",
    attachments: [],
    correctiveActions: "Advise him to go and apply for permit and no work without permit",
    actionItems: [],
    status: "Approval Pending",
    createdBy: "Saheed Tayo Oseni(E-FIN-0033)",
    createdAt: "2024-10-16T16:51:33Z",
    shared: false,
  },
  {
    id: "7",
    number: "OBS-2024-0000009",
    date: "2024-12-11",
    businessUnit: "XOM Well Maintenance",
    observer: "Hamed Al Saghir Humaid Al Maharbi",
    observerEmail: "hmaharbi@xomoman.com",
    position: "Operator Slickline",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "Observed one of crew during rig up he was using hammer opposite side.",
    observationType: "Unsafe",
    category: "Equipment Safety",
    attachments: [],
    correctiveActions: "Always ensure using hammer in right position.",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2024-12-13T10:23:40Z",
    shared: false,
  },
  {
    id: "8",
    number: "OBS-2024-0000010",
    date: "2024-12-11",
    businessUnit: "XOM Well Maintenance",
    observer: "Zahir Said Hamed Al Touqi",
    observerEmail: "ztouqi@xomoman.com",
    position: "Operations supervisor",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "Observed crew was using leather gloves instead of impact gloves.",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "Employee was not aware.",
    actionItems: [],
    status: "Approval Pending",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2024-12-13T10:32:04Z",
    shared: false,
  },
  {
    id: "9",
    number: "OBS-2024-0000011",
    date: "2024-12-13",
    businessUnit: "XOM Well Maintenance",
    observer: "Zakariya Yahya Al Busaidi",
    observerEmail: "zbusaidi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed mechanic crew member was not wearing the proper gloves while fixing the AC pipes.",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "Mechanic should wear the leather gloves to avoid finger injury.",
    actionItems: [],
    status: "Approval Pending",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2024-12-14T10:10:35Z",
    shared: false,
  },
  {
    id: "10",
    number: "OBS-2024-0000038",
    date: "2024-12-22",
    businessUnit: "Falcon Oilfield Services",
    observer: "Hamed Saif Al Shukaili",
    observerEmail: "hshukaili@falconoilfield.com",
    position: "Wireline Operator",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: false,
    description: "L-4 We use pull stick for standby.",
    observationType: "Safe",
    category: "Equipment Safety",
    attachments: [],
    correctiveActions: "For the safety of our hands.",
    actionItems: [],
    status: "Overdue",
    createdBy: "AL-Zaina Zayid AL-Rujaibi(L-FINT-00039)",
    createdAt: "2025-02-12T14:39:05Z",
    shared: false,
  },
  {
    id: "11",
    number: "OBS-2025-0000012",
    date: "2025-01-01",
    businessUnit: "XOM Oman",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed Helper using proper PPE while maintain housekeeping in wash bay",
    observationType: "Safe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "Appreciated for good conduct",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-01T15:07:26Z",
    shared: false,
  },
  {
    id: "12",
    number: "OBS-2025-0000013",
    date: "2025-01-01",
    businessUnit: "XOM Oman",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "HSE",
    location: "Camp",
    nearMiss: false,
    draft: false,
    description: "LED light has been fixed all camp rooms",
    observationType: "Safe",
    category: "Electrical Safety",
    attachments: [],
    correctiveActions: "Appreciated for good conduct",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-01T15:22:37Z",
    shared: false,
  },
  {
    id: "13",
    number: "OBS-2025-0000014",
    date: "2025-01-01",
    businessUnit: "XOM Oman",
    observer: "Mohammed Saleh Saif Al Zakwani",
    observerEmail: "mzakwani@xomoman.com",
    position: "Foreman",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "I observe the waste tank was full of water",
    observationType: "Unsafe",
    category: "Environmental",
    attachments: [],
    correctiveActions: "Maintain barrier tap and inform management to bring suck tanker",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-01T15:33:18Z",
    shared: false,
  },
  {
    id: "14",
    number: "OBS-2025-0000015",
    date: "2025-01-01",
    businessUnit: "XOM Oman",
    observer: "Mohammed Saleh Saif Al Zakwani",
    observerEmail: "mzakwani@xomoman.com",
    position: "Foreman",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Found old chemical drums & bags dumped on yard outside",
    observationType: "Unsafe",
    category: "Environmental",
    attachments: [],
    correctiveActions: "Informed management for transferring and disposal",
    actionItems: [],
    status: "NoA",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-01T15:37:02Z",
    shared: false,
  },
  {
    id: "15",
    number: "OBS-2025-0000016",
    date: "2025-01-09",
    businessUnit: "XOM Oman",
    observer: "Mohammed Humaid Salim Al Alawi",
    observerEmail: "malawi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "While a crew member was using a hammer to tighten a connection, two other crew members were positioned directly in front of him. This situation may pose a risk of injury to those in close proximity, as there is a possibility of being struck by the hammer or any debris on the line of fire.",
    observationType: "Unsafe",
    category: "Line of Fire",
    attachments: [],
    correctiveActions: "Share the learning with all crew regarding the CCTV Capture",
    actionItems: [],
    status: "Closed",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-12T08:05:58Z",
    shared: false,
  },
  {
    id: "16",
    number: "OBS-2025-0000017",
    date: "2025-01-09",
    businessUnit: "XOM Oman",
    observer: "Mohammed Humaid Salim Al Alawi",
    observerEmail: "malawi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "CCTV Capture - The operator stopped the assistant and provided clear guidance on how to safely operate the valve, emphasizing the correct posture to adopt when handling the valve, particularly in the event of trapped pressure.",
    observationType: "Safe",
    category: "Supervision",
    attachments: [],
    correctiveActions: "Share the learning from the CCTV with all crews and inform them to take extra care while they are operating the valve on the X-Tree",
    actionItems: [],
    status: "Closed",
    createdBy: "HSE FWM(HSE FWM)",
    createdAt: "2025-01-12T08:10:29Z",
    shared: false,
  },
  {
    id: "17",
    number: "OBS-2025-0000018",
    date: "2025-01-21",
    businessUnit: "XOM Oman",
    observer: "Zakariya Yahya Al Busaidi",
    observerEmail: "zbusaidi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed assistant giving signal while reversing the unit, the assistant was in a proper distance to give directions to the driver.",
    observationType: "Safe",
    category: "Road Safety",
    attachments: [],
    correctiveActions: "Appreciated the Assistant for good practice.",
    actionItems: [],
    status: "NoA",
    createdBy: "Zakariya Yahya Al Busaidi(L-HIR-0115)",
    createdAt: "2025-01-23T10:08:24Z",
    shared: false,
  },
  {
    id: "18",
    number: "OBS-2025-0000019",
    date: "2025-01-19",
    businessUnit: "XOM Well Maintenance",
    observer: "Zakariya Yahya Al Busaidi",
    observerEmail: "zbusaidi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "Observe one crew member did not use 3 point contact while disbanding from the scaffolding ladder. which could lead to trip hazard.",
    observationType: "Unsafe",
    category: "Working at Height",
    attachments: [],
    correctiveActions: "Stopped the employee and explained the hazard associated for this unsafe practice and importance of using 3 point contact. Action was taken in spot. as well as been shared to the team during morning meeting.",
    actionItems: [],
    status: "NoA",
    createdBy: "Zakariya Yahya Al Busaidi(L-HIR-0115)",
    createdAt: "2025-01-23T10:12:44Z",
    shared: false,
  },
  {
    id: "19",
    number: "OBS-2025-0000020",
    date: "2025-01-23",
    businessUnit: "XOM Well Maintenance",
    observer: "Zakariya Yahya Al Busaidi",
    observerEmail: "zbusaidi@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed while lifting the lubricator to the unit, the area was barricaded, push and pull stick was used and the operator informed the rest that they are having lifting operation here in base.",
    observationType: "Safe",
    category: "Lifting Operations",
    attachments: [],
    correctiveActions: "Appreciated the Operator for such good practice.",
    actionItems: [],
    status: "NoA",
    createdBy: "Zakariya Yahya Al Busaidi(L-HIR-0115)",
    createdAt: "2025-01-23T10:18:27Z",
    shared: false,
  },
  {
    id: "20",
    number: "OBS-2025-0000021",
    date: "2025-01-15",
    businessUnit: "XOM Well Maintenance",
    observer: "Hemza Benchelloug",
    observerEmail: "hbenchelloug@xomoman.com",
    position: "OTHERS",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed employee lifting X-over, he used the right lifting technics and good spinal position. Well done for the employee.",
    observationType: "Safe",
    category: "Manual Handling",
    attachments: [],
    correctiveActions: "NA, encourage the employee continuing his good lifting behavior",
    actionItems: [],
    status: "NoA",
    createdBy: "Hemza Benchelloug(E-FWM-0120)",
    createdAt: "2025-01-23T10:59:57Z",
    shared: false,
  },
  {
    id: "21",
    number: "OBS-2025-0000022",
    date: "2025-01-28",
    businessUnit: "XOM Oman",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "OTHERS",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "I saw someone not wearing helmet",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "Asked crew to wear helmet",
    actionItems: [],
    status: "NoA",
    createdBy: "Syed Sadaqat ADMIN(ADMIN)",
    createdAt: "2025-01-28T07:55:59Z",
    shared: false,
  },
  {
    id: "22",
    number: "OBS-2025-0000023",
    date: "2025-01-31",
    businessUnit: "XOM Well Maintenance",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "CCTV- Capture observed with SL-23 @BRNW-67 during lifting lubricator employee using pull & push stick to avoid hand and finger crush",
    observationType: "Safe",
    category: "Lifting Operations",
    attachments: [],
    correctiveActions: "",
    actionItems: [],
    status: "NoA",
    createdBy: "Abdallah Ali Mohammed Al Busaidy(L-FWM-0049)",
    createdAt: "2025-01-31T09:26:28Z",
    shared: false,
  },
  {
    id: "23",
    number: "OBS-2025-0000025",
    date: "2025-01-28",
    businessUnit: "Falcon Oilfield Services",
    observer: "Waqas Ahmed",
    observerEmail: "wahmed@falconoilfield.com",
    position: "Field Engineer",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "During the Start of my hitch on 28th January i observed all the crew members are wearing full PPE including the Safety Shoes, Coverall, Hard hat and Suitable Gloves while working in the shop. I appreciated the full compliance of the crew fellows.",
    observationType: "Safe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "",
    actionItems: [],
    status: "NoA",
    createdBy: "Waqas Ahmed(E-NSE-0216)",
    createdAt: "2025-02-01T09:32:23Z",
    shared: false,
  },
  {
    id: "24",
    number: "OBS-2025-0000026",
    date: "2025-01-29",
    businessUnit: "Falcon Oilfield Services",
    observer: "Waqas Ahmed",
    observerEmail: "wahmed@falconoilfield.com",
    position: "Field Engineer",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "During the process of opening the Sinker Bar Adaptor, the crew used proper hand tools, securing the tool with a chain and using a pipe wrench. As it was hard to open, they chose a higher-capacity pipe wrench instead of a cheat pipe to safely increase torque.",
    observationType: "Safe",
    category: "Equipment Safety",
    attachments: [],
    correctiveActions: "Appreciated The crew's commitment to safety was commendable, choosing proper tools to ensure a controlled operation.",
    actionItems: [],
    status: "NoA",
    createdBy: "Waqas Ahmed(E-NSE-0216)",
    createdAt: "2025-02-01T09:45:18Z",
    shared: false,
  },
  {
    id: "25",
    number: "OBS-2025-0000030",
    date: "2025-02-12",
    businessUnit: "Falcon Oilfield Services",
    observer: "AL-Zaina Zayid AL-Rujaibi",
    observerEmail: "azrujaibi@falconoilfield.com",
    position: "Field Engineer",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Good lifting techniques. (Manual Handling)",
    observationType: "Safe",
    category: "Manual Handling",
    attachments: [],
    correctiveActions: "Appreciate crew members among the base staff.",
    actionItems: [],
    status: "NoA",
    createdBy: "AL-Zaina Zayid AL-Rujaibi(L-FINT-00039)",
    createdAt: "2025-02-12T09:17:41Z",
    shared: false,
  },
  {
    id: "26",
    number: "OBS-2025-0000031",
    date: "2025-02-12",
    businessUnit: "Falcon Oilfield Services",
    observer: "AL-Zaina Zayid AL-Rujaibi",
    observerEmail: "azrujaibi@falconoilfield.com",
    position: "Field Engineer",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed employee was working without wearing helmet.",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "Stopped him and advice to wear helmet while working.",
    actionItems: [],
    status: "Closed",
    createdBy: "Zakiya Salim Al Naabi(L-FIN-0034)",
    createdAt: "2025-02-12T11:10:22Z",
    shared: false,
  },
  {
    id: "27",
    number: "OBS-2025-0000032",
    date: "2025-01-10",
    businessUnit: "Falcon Oilfield Services",
    observer: "Basim Abdullah Al Shaibani",
    observerEmail: "bshaibani@falconoilfield.com",
    position: "Wireline Operator",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: true,
    description: "Failure to place warning signs to alert visitors to the presence of danger in the workplace.",
    observationType: "Unsafe",
    category: "Communication",
    attachments: [],
    correctiveActions: "Place signs in a convenient location to alert visitors.",
    actionItems: [],
    status: "NoA",
    createdBy: "AL-Zaina Zayid AL-Rujaibi(L-FINT-00039)",
    createdAt: "2025-02-12T13:34:04Z",
    shared: false,
  },
  {
    id: "28",
    number: "OBS-2025-0000033",
    date: "2025-01-23",
    businessUnit: "Falcon Oilfield Services",
    observer: "Muhammad Zeeshan Qadir",
    observerEmail: "mqadir@falconoilfield.com",
    position: "Field Engineer",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: true,
    description: "The crew member while holding the tag line stay out of line of fire.",
    observationType: "Safe",
    category: "Line of Fire",
    attachments: [],
    correctiveActions: "Stay out of the line of fire.",
    actionItems: [],
    status: "NoA",
    createdBy: "AL-Zaina Zayid AL-Rujaibi(L-FINT-00039)",
    createdAt: "2025-02-12T13:43:26Z",
    shared: false,
  },
  {
    id: "29",
    number: "OBS-2025-0000042",
    date: "2025-02-13",
    businessUnit: "XOM Oman",
    observer: "Arwa Nasser AL-Habsi",
    observerEmail: "ahabsi@xomoman.com",
    position: "HSE",
    location: "Store",
    nearMiss: true,
    draft: false,
    description: "The metal grates covering the drainage system appear to be misaligned and partially broken. Some grates are bent and missing sections, posing a safety hazard for pedestrians and vehicles. Lack of maintenance.",
    observationType: "Unsafe",
    category: "General Safety",
    attachments: [],
    correctiveActions: "A black metal post with red-and-white caution tape was already placed to warn pedestrians and drivers. The issue was reported to the relevant local authorities for immediate action.",
    actionItems: [],
    status: "Closed",
    createdBy: "Arwa Nasser AL-Habsi(L-XOM-0049)",
    createdAt: "2025-02-13T09:17:52Z",
    shared: false,
  },
  {
    id: "30",
    number: "OBS-2025-0000043",
    date: "2025-02-12",
    businessUnit: "XOM Drilling System",
    observer: "Arwa Nasser AL-Habsi",
    observerEmail: "ahabsi@xomoman.com",
    position: "HSE",
    location: "Store",
    nearMiss: true,
    draft: false,
    description: "The eyewash available in all UNITS has expired.",
    observationType: "Unsafe",
    category: "Emergency Preparedness",
    attachments: [],
    correctiveActions: "Request an additional quantity of eyewash to be supplied for both units and the base",
    actionItems: [],
    status: "Closed",
    createdBy: "Arwa Nasser AL-Habsi(L-XOM-0049)",
    createdAt: "2025-02-13T14:17:16Z",
    shared: false,
  },
  {
    id: "31",
    number: "OBS-2025-0000045",
    date: "2025-02-11",
    businessUnit: "XOM Well Maintenance",
    observer: "Mohammed Humaid Salim Al Alawi",
    observerEmail: "malawi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "Observed one of the team member were working on top of the scaffolding and he was tight the lubricator in the scaffolding without using the proper hand gloves",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "I already engage with crew regarding this issue and it's been closed",
    actionItems: [],
    status: "NoA",
    createdBy: "Mohammed Humaid Salim Al Alawi(L-FWM-0033)",
    createdAt: "2025-02-14T08:51:43Z",
    shared: false,
  },
  {
    id: "32",
    number: "OBS-2025-0000046",
    date: "2025-02-10",
    businessUnit: "XOM Well Maintenance",
    observer: "Mohammed Humaid Salim Al Alawi",
    observerEmail: "malawi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "CCTV Capture: Good practice while using the handrail team member using 3 contacts",
    observationType: "Safe",
    category: "Working at Height",
    attachments: [],
    correctiveActions: "Appreciate the crew",
    actionItems: [],
    status: "NoA",
    createdBy: "Mohammed Humaid Salim Al Alawi(L-FWM-0033)",
    createdAt: "2025-02-14T08:55:21Z",
    shared: false,
  },
  {
    id: "33",
    number: "OBS-2025-0000047",
    date: "2025-02-07",
    businessUnit: "XOM Well Maintenance",
    observer: "Mohammed Humaid Salim Al Alawi",
    observerEmail: "malawi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "CCTV Capture: Team member crossing under the flow line and it may cause back injury to him",
    observationType: "Unsafe",
    category: "Manual Handling",
    attachments: [],
    correctiveActions: "Review the CCTV with all crew members to avoid such Behavior",
    actionItems: [],
    status: "NoA",
    createdBy: "Mohammed Humaid Salim Al Alawi(L-FWM-0033)",
    createdAt: "2025-02-14T08:58:46Z",
    shared: false,
  },
  {
    id: "34",
    number: "OBS-2025-0000059",
    date: "2025-02-15",
    businessUnit: "XOM Well Maintenance",
    observer: "Waleed Saleem Thaleth Al Omairi",
    observerEmail: "womairi@xomoman.com",
    position: "Operations supervisor",
    location: "Daleel Site",
    nearMiss: false,
    draft: false,
    description: "It was noticed that the person was not wearing gloves, which is dangerous and may cause amputation of the fingers.",
    observationType: "Unsafe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "I stopped the person, gave him advice and guidance, and then ordered him to put on the gloves.",
    actionItems: [],
    status: "NoA",
    createdBy: "Waleed Saleem Thaleth Al Omairi(L-FWM-0112)",
    createdAt: "2025-02-15T09:20:52Z",
    shared: false,
  },
  {
    id: "35",
    number: "OBS-2025-0000062",
    date: "2025-02-14",
    businessUnit: "XOM Well Maintenance",
    observer: "Zakariya Yahya Al Busaidi",
    observerEmail: "zbusaidi@xomoman.com",
    position: "HSE",
    location: "Well Site-Standalone",
    nearMiss: false,
    draft: false,
    description: "Observed one of the crew member was hammering and the other employee was standing nearby the hammering location.",
    observationType: "Unsafe",
    category: "Line of Fire",
    attachments: [],
    correctiveActions: "Intervened immediately, stopped the crew member and explained the risk of hammering without using finger sever and how can the other employee get effected if the hammer got slipped.",
    actionItems: [],
    status: "NoA",
    createdBy: "Zakariya Yahya Al Busaidi(L-HIR-0115)",
    createdAt: "2025-02-15T10:33:39Z",
    shared: false,
  },
  {
    id: "36",
    number: "OBS-2025-0000376",
    date: "2025-06-24",
    businessUnit: "XOM Drilling System",
    observer: "Idris Surur AlAlawi",
    observerEmail: "ialawi@xomoman.com",
    position: "Dirrectional Driller",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: false,
    description: "Observed good team work when offloading equipment from truck, mustaed steps followed, and people were out of line of fire.",
    observationType: "Safe",
    category: "Lifting Operations",
    attachments: [],
    correctiveActions: "Appreciated the teamwork.",
    actionItems: [],
    status: "NoA",
    createdBy: "Idris Surur AlAlawi(L-FDS-0012)",
    createdAt: "2025-06-24T11:45:42Z",
    shared: false,
  },
  {
    id: "37",
    number: "OBS-2025-0000378",
    date: "2025-06-24",
    businessUnit: "XOM Drilling System",
    observer: "Ahmed Mohammed Osama Ahmed",
    observerEmail: "aahmed@xomoman.com",
    position: "Dirrectional Driller",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: false,
    description: "Fire extinguisher assigned to MWD Cabin U2 present at Rig-49 is due for inspection on 12-Jul-25 (almost 16 days from now). Please arrange a replacement before this due date.",
    observationType: "At Risk",
    category: "Fire Safety",
    attachments: [],
    correctiveActions: "Informed The Base that a Fire extinguisher replacement has to be mobilized to Rig-49 before the current one inspection due date expires 12-Jul-25. Assigned an action item on the Nizwa Base on Himaya.",
    actionItems: [
      {
        id: "ACT-037-001",
        type: "Preventive Action",
        action: "Mobilize replacement fire extinguisher to Rig-49",
        actionParty: "Nizwa Base",
        approver: "HSE Manager",
        priority: "High",
        raisedDate: "2025-06-24",
        targetDate: "2025-07-10",
        status: "Open",
        attachments: [],
      },
    ],
    status: "Approval Pending",
    createdBy: "I A Xom(00012)",
    createdAt: "2025-06-24T13:54:11Z",
    shared: false,
  },
  {
    id: "38",
    number: "OBS-2025-0000379",
    date: "2025-06-25",
    businessUnit: "XOM Drilling System",
    observer: "Nasser Khamis AlRawahi",
    observerEmail: "nrawahi@xomoman.com",
    position: "Dirrectional Driller",
    location: "Well Site-Rig",
    nearMiss: false,
    draft: true,
    description: "Observed driver during the trip to camp site he followed all driving practices in place no over speeding following lane traffic and no tailgating",
    observationType: "Safe",
    category: "Road Safety",
    attachments: [],
    correctiveActions: "Appreciated for good driving",
    actionItems: [],
    status: "NoA",
    createdBy: "Nasser Khamis AlRawahi(L-FDS-0020)",
    createdAt: "2025-06-25T00:34:25Z",
    shared: false,
  },
  {
    id: "39",
    number: "OBS-2025-0000380",
    date: "2025-06-25",
    businessUnit: "XOM Drilling System",
    observer: "Nasser Khamis AlRawahi",
    observerEmail: "nrawahi@xomoman.com",
    position: "Dirrectional Driller",
    location: "Well Site-Rig",
    nearMiss: true,
    draft: true,
    description: "Observed that one of the ditch covers was not installed back properly after cleaning out the ditch",
    observationType: "Unsafe",
    category: "Housekeeping",
    attachments: [],
    correctiveActions: "I put the cover on properly to avoid a trip hazard",
    actionItems: [],
    status: "NoA",
    createdBy: "Nasser Khamis AlRawahi(L-FDS-0020)",
    createdAt: "2025-06-25T00:42:01Z",
    shared: false,
  },
  {
    id: "40",
    number: "OBS-2025-0000383",
    date: "2025-06-25",
    businessUnit: "XOM Well Maintenance",
    observer: "Fahad Majiid",
    observerEmail: "fmajiid@xomoman.com",
    position: "OTHERS",
    location: "Camp",
    nearMiss: true,
    draft: false,
    description: "Found steel wool piece in food.",
    observationType: "Unsafe",
    category: "General Safety",
    attachments: [],
    correctiveActions: "Informed diner team, but no response",
    actionItems: [],
    status: "NoA",
    createdBy: "Fahad Majiid(BARIK-XWM-003)",
    createdAt: "2025-06-25T18:26:22Z",
    shared: false,
  },
  {
    id: "41",
    number: "OBS-2025-0000421",
    date: "2025-07-05",
    businessUnit: "Falcon Oilfield Services",
    observer: "Syed Sadaqat HSEM",
    observerEmail: "ssadaqat@falconoilfield.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "AZ-06 - MAN 1976 YD for driving unsafely on 2025-07-05 at 10:48:28. The system recorded an SP2000 violation—overspeeding (140 km/h) at location Latitude 19.243139, Longitude 56.471778. This incident was investigated and found to be a false/faulty event.",
    observationType: "At Risk",
    category: "Road Safety",
    attachments: [],
    correctiveActions: "Investigate event",
    actionItems: [],
    status: "Closed",
    createdBy: "Syed Sadaqat HSEM(FOFS-2025-01)",
    createdAt: "2025-07-10T10:09:47Z",
    shared: false,
  },
  {
    id: "42",
    number: "OBS-2025-0000419",
    date: "2025-07-09",
    businessUnit: "XOM Well Maintenance",
    observer: "Khalid Nasser Salim Al Hakmani",
    observerEmail: "khalid@xomoman.com",
    position: "Operations supervisor",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "Observed mechanic using full PPE while working",
    observationType: "Safe",
    category: "PPE Compliance",
    attachments: [],
    correctiveActions: "",
    actionItems: [],
    status: "NoA",
    createdBy: "Abdallah Ali Mohammed Al Busaidy(L-FWM-0049)",
    createdAt: "2025-07-09T10:39:31Z",
    shared: false,
  },
  {
    id: "43",
    number: "OBS-2025-0000420",
    date: "2025-07-09",
    businessUnit: "XOM Well Maintenance",
    observer: "Abdallah Ali Mohammed Al Busaidy",
    observerEmail: "abusaidy@xomoman.com",
    position: "HSE",
    location: "Workshop/Base",
    nearMiss: false,
    draft: false,
    description: "PCE helper while lifting heavy tool using forklift truck",
    observationType: "Safe",
    category: "Lifting Operations",
    attachments: [],
    correctiveActions: "",
    actionItems: [],
    status: "NoA",
    createdBy: "Abdallah Ali Mohammed Al Busaidy(L-FWM-0049)",
    createdAt: "2025-07-09T10:42:05Z",
    shared: false,
  },
]
