export interface User {
  id: string
  payrollNo: string
  name: string
  email: string
  role: "ADMIN SYSTEM" | "MANAGEMENT" | "SITE MANAGER" | "SITE MANAGER - Global" | "HSE ADMIN" | "HSE" | "HR" | "MASTER USER" | "USER" | "USER - JM"
  designation: string
  businessUnit: string
  status: "Active" | "Inactive"
}

export const users: User[] = [
  { id: "1", payrollNo: "XOM-DS-CON-0011", name: "Ahmed Abdalhamid Abbady", email: "aabbady@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "2", payrollNo: "XDS-DS--014", name: "Ahmed AB", email: "2@xomoman.com", role: "MANAGEMENT", designation: "Managing Director", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "3", payrollNo: "1224", name: "xom xom xom (S)", email: "xom23@xomoman.com", role: "USER", designation: "Technical Director", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "4", payrollNo: "2ejd", name: "lmwdq kqnef ewqf (S)", email: "1@xomoman.com", role: "USER", designation: "Delivery Assurance Assistant Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "5", payrollNo: "L-NSE-0281", name: "Ahmed Mohammed AL-Habsi", email: "ahabsi@falconofs.com", role: "USER", designation: "Store Man & Journey Manager", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "6", payrollNo: "L-XOM-0043", name: "Ib Hi Al (S)", email: "xom@xomoman.com", role: "USER", designation: "Electrician", businessUnit: "XOM Oman", status: "Inactive" },
  { id: "7", payrollNo: "i", name: "q293 dwd (S)", email: "xom1@xomoman.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "8", payrollNo: "E-FDS-0036", name: "Ahmed Mohammed Osama Ahmed", email: "aosama@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "9", payrollNo: "L-XOM-0052", name: "Ahmed Khalid Ahmed Al Zakwani", email: "aalzakwani@xomoman.com", role: "USER - JM", designation: "Journey manager / store keeper", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "10", payrollNo: "L-328543", name: "IT Admin XOM", email: "xom-it-admin@xomoman.com", role: "ADMIN SYSTEM", designation: "System Administrator", businessUnit: "XOM Oman", status: "Active" },
  { id: "11", payrollNo: "Approver", name: "Syed Sadaqat Approver", email: "syedsadaqat2494326@gmail.com", role: "MASTER USER", designation: "HSE Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "12", payrollNo: "430974", name: "Rustam Khasanshin", email: "rkhasanshin@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "13", payrollNo: "L-XDS-0055", name: "Shaker Al Kathiri", email: "skathiri@xomoman.com", role: "USER", designation: "Directional Driller Trainee", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "14", payrollNo: "L-XOM-0024", name: "Yousuf Mohsen Al-Hashmi", email: "yalhashmi@xomoman.com", role: "USER", designation: "MWD Trainee", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "15", payrollNo: "L-XOM-0040", name: "Ibrahim Hilal Albusaidi (S)", email: "ibusaidi@xomoman.com", role: "USER", designation: "General Manager", businessUnit: "XOM Oman", status: "Active" },
  { id: "16", payrollNo: "L-NSE-0286", name: "Mohammed Hilal Ahmed AlKindi", email: "m.alkindi@falconofs.com", role: "USER - JM", designation: "Workshop Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "17", payrollNo: "NSE-0285", name: "Sameh Salim AlHarthy", email: "sharthy@falconofs.com", role: "USER", designation: "Payroll Officer", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "18", payrollNo: "L-NSE-0284", name: "Laila Ahmed AlKindi", email: "lkindi@falconofs.com", role: "HR", designation: "Admin and HR", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "19", payrollNo: "L-NSE-0283", name: "Jabir Mohammed AlMahrouqi", email: "jmahrouqi@falconofs.com", role: "USER", designation: "Base Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "20", payrollNo: "L-NSE-0282", name: "Mohammed Sulaiman Hassan Al-Balushi", email: "mbalushi@falconstaff.org", role: "USER", designation: "TCP Operator", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "21", payrollNo: "L-NSE-0280", name: "Shihab Hamad Mubarak Al-Abri", email: "salabri@falconofs.com", role: "MANAGEMENT", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "22", payrollNo: "L-NSE-0279", name: "Tariq Salim Said Al-Kalbani", email: "tkalbani@falconofs.com", role: "MANAGEMENT", designation: "Base Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "23", payrollNo: "L-NSE-0278", name: "Abdul Rahim Saif Ahmed Al-Kindi", email: "a.kindi@falconofs.com", role: "SITE MANAGER", designation: "Base Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "24", payrollNo: "L-NSE-0277", name: "Hamed Hamood Said Al-Busaidi", email: "hbusaidi@falconstaff.org", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "25", payrollNo: "L-NSE-0274", name: "Ali Rashid Moahmmed Al-Sawafi", email: "asawafi@falconstaff.org", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "26", payrollNo: "L-NSE-0272", name: "Juma Khalid Al-Sabari", email: "jsabri@falconofs.com", role: "USER", designation: "TCP Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "27", payrollNo: "L-NSE-0271", name: "Anwar Saif Abdullah Al-KhayarI", email: "akhayari@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "28", payrollNo: "L-NSE-0270", name: "Salim Hamood Salim Al-Shekaili", email: "s.alshekaili@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "29", payrollNo: "L-NSE-0266", name: "Sharifa Ahmed Al-Sawwafi", email: "ssawwafi@falconofs.com", role: "USER", designation: "Accountant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "30", payrollNo: "L-NSE-0262", name: "Idris Hamid Al-Mayahi", email: "imayahi@falconofs.com", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "31", payrollNo: "L-NSE-0261", name: "Nasser Hamoud Al-Burtamani", email: "nburtamani@falconofs.com", role: "USER", designation: "TCP Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "32", payrollNo: "L-NSE-0248", name: "Huda Salim Sulaiman AlJahwari", email: "hjahwari@falconstaff.org", role: "USER", designation: "HSE Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "33", payrollNo: "NSE-0256", name: "Hamood Hamed AlKhusaibi", email: "hkusaibi@falconstaff.org", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "34", payrollNo: "L-NSE-0", name: "Samira Hamed Al Shukaili", email: "sam.shukaili@falconofs.com", role: "USER", designation: "Supply Chain Leader", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "35", payrollNo: "7804967", name: "Faisal Ishaqi", email: "f.alishaqi@falconofs.com", role: "USER", designation: "Finance manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "36", payrollNo: "LNSE0269", name: "Ibrahim Breiki", email: "ibreiki@falconofs.com", role: "MANAGEMENT", designation: "Operations Manager", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "37", payrollNo: "L-XDS-0050", name: "MAZIN Salim Yahya AL AZWANI", email: "mazwani@xomoman.com", role: "USER", designation: "MWD Trainee", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "38", payrollNo: "E-NSE-0222", name: "Zeeshan Qamar", email: "zeeshan@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "39", payrollNo: "E-NSE-0217", name: "yusral Bin Jamuir Sunur", email: "ysunur@falconstaff.org", role: "USER", designation: "Sonde Technician", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "40", payrollNo: "L-HIR-0046", name: "Waleed Mohammed Al Alawi", email: "walawi@falconofs.com", role: "USER", designation: "Mukaizna Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "41", payrollNo: "E-NSE-0226", name: "Tamer Mohammed Farghaly", email: "t.farghaly@falconstaff.org", role: "USER", designation: "PCE Specialist", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "42", payrollNo: "Tra001-XOM", name: "Muzna Mahfoodh Al Hadi", email: "mhadi@xomoman.com", role: "HR", designation: "Admin and HR", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "43", payrollNo: "E-HIR-0076", name: "Muhammad Zeeshan Qadir", email: "mqadir@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "44", payrollNo: "L-HIR-0044", name: "Mohammed Juma Al Rabaani", email: "mrabaani@falconofs.com", role: "USER", designation: "Maintenance Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "45", payrollNo: "L-NSE-0110", name: "Ishaq Ali Al Afeefi", email: "fofs-nz-elfm@falconofs.com", role: "USER", designation: "Workshop Foremen", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "46", payrollNo: "L-HIR-0041", name: "Hamed Yaqoob Al Yahyai", email: "hyahyai@falconstaff.org", role: "USER", designation: "Mukaizna Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "47", payrollNo: "L-HIR-0039", name: "Hamed Saif Al Shukaili", email: "hshekaili@falconofs.com", role: "USER", designation: "Field Operator", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "48", payrollNo: "L-HIRC-0001", name: "Bati Al yaqoubi", email: "bjuma@falconstaff.org", role: "USER", designation: "Mechanic", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "49", payrollNo: "L-FDS-0026", name: "Asad Saed Al-Rumaidhi", email: "aalrumaidhi@xomoman.com", role: "USER", designation: "Electronics Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "50", payrollNo: "L-HIRC-0002", name: "Ali Mabrook Al Tobi", email: "alitobi@falconstaff.org", role: "USER", designation: "PCE Specialist", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "51", payrollNo: "L-FDS-0019", name: "Abdullah Khamis Al-Hinai", email: "ahinai@xomoman.com", role: "USER", designation: "Motor Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "52", payrollNo: "E-XDS-0053", name: "Mounir Nessal", email: "mnessal@xomoman.com", role: "HSE ADMIN", designation: "Operations Manager", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "53", payrollNo: "L-HIR-0042", name: "Khalid Said Al Hothaly", email: "khudhaili@falconofs.com", role: "USER", designation: "Mukaizna Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "54", payrollNo: "L-FINT-00017", name: "Adil AL-Shukaili", email: "ashukili@falconstaff.org", role: "USER", designation: "Field Engineer (Trainee)", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "55", payrollNo: "XOM-DS-SUB-001", name: "Sanaullah PIR Muhammad Khan", email: "sanaullahkh12374@gmail.com", role: "USER", designation: "Helper", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "56", payrollNo: "L-XOMT-0037", name: "Muddathir Al Fahdi", email: "malfahdi@xomoman.com", role: "USER", designation: "Tool Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "57", payrollNo: "XOM-DS-CON-002", name: "Mazin Abdullah Al Kindi", email: "malkindi@xomoman.com", role: "USER", designation: "Electronics Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "58", payrollNo: "XOM-DS-CON-012", name: "Humaid Al Waili", email: "hwaili@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "59", payrollNo: "XOM-DS-CON-013", name: "Al Azhar Al Anbori", email: "humaid1979s@icloud.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "60", payrollNo: "L-XOMT-0015", name: "Ahmed Al Khamisi", email: "akhamisi@xomoman.com", role: "USER - JM", designation: "Journey manager / store keeper", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "61", payrollNo: "L-XOM-0042", name: "I H Al (S)", email: "i@xomoman.com", role: "USER", designation: "General Manager", businessUnit: "XOM Oman", status: "Active" },
  { id: "62", payrollNo: "22440026", name: "Shaker Al Kathiri", email: "skathiri@xon.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "63", payrollNo: "XOM-DS-CON-004", name: "AbdelRahman Gamal", email: "agamal@xomoman.com", role: "SITE MANAGER", designation: "Reliability Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "64", payrollNo: "FOFS-2025-01", name: "Syed Sadaqat HSEM", email: "ssadaqat@falconofs.com", role: "SITE MANAGER - Global", designation: "QHSE Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "65", payrollNo: "L-FINT-00038", name: "Turki Al Kharusi", email: "tkharusi@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "66", payrollNo: "FDS-Consultant", name: "Salim Saif Al-Abri", email: "sabri@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "67", payrollNo: "L-FINT-00022", name: "Omar Khalfan Al-Amri", email: "oaamri@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "68", payrollNo: "L-FDS-0046", name: "Mahmood Mohammed Mustafa Najjar", email: "mnajjar@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "69", payrollNo: "L-FINT-00020", name: "Liyth Ambusaidi", email: "lambusaidi@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "70", payrollNo: "L-FDS-0043", name: "Abdullah Sulaiman Hamdan Al Aamri", email: "aamri@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "71", payrollNo: "L-FDS-0056", name: "Ahmed Hamed Al JUFAILI", email: "ajufaily@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "72", payrollNo: "L-FDS-0032", name: "Abdullah Sulaiman Al-Aamri", email: "aamri@gmail.com", role: "USER", designation: "Directional Driller Trainee", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "73", payrollNo: "XOM-DS-C-006", name: "Ahmed Khalid Ahmed Al Zakwani", email: "azakwani@xomoman.com", role: "USER - JM", designation: "Field Operator", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "74", payrollNo: "XOM-DS-031", name: "Hashim Ali Mubarak Al Farsi", email: "hfarsi@xomoman.com", role: "SITE MANAGER", designation: "Service Quality", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "75", payrollNo: "E-NSE-0228", name: "Sohail Khan Jadoon", email: "sjadoon@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "76", payrollNo: "XWM-SUB-004", name: "Suhail Mohammed", email: "suhail.mohammed@barikgroup.com", role: "USER", designation: "3rd Party Contractor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "77", payrollNo: "L-FINT-00019", name: "BASIM Ghasi AL Rahbi", email: "b.rahbi@falconstaff.org", role: "USER", designation: "Field Engineer (Trainee)", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "78", payrollNo: "L-FINT-00018", name: "Asad Said AL-Yahyaai", email: "a.yayaai@falconstaff.org", role: "USER", designation: "Field Engineer (Trainee)", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "79", payrollNo: "L-HIR-0119", name: "Mohammed Hamed Ali Al Shaaili", email: "mohd95516054@gmail.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "80", payrollNo: "BARIK-XWM-002", name: "Faisal Said Khalfan Al Harthy", email: "faisalg3588455@gmail.com", role: "USER", designation: "WHM Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "81", payrollNo: "BARIK-XWM-003", name: "Fahad Majiid", email: "fahadhpam@gmail.com", role: "USER", designation: "WHM Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "82", payrollNo: "BARIK-XWM-01", name: "Nasser Al Mamari", email: "nasser88almamari@gmail.com", role: "USER", designation: "WHM Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "83", payrollNo: "L-HIR-0127", name: "Montasar Ahmed Rashid Al-Habsi", email: "mun9911@icloud.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "84", payrollNo: "E-NSE-0221", name: "Islam Mohamad Gaber", email: "islam.gaber@falconofs.com", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "85", payrollNo: "E-NSE-0224", name: "Hammad Shoukat", email: "mhammad@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "86", payrollNo: "L-FINT-00039", name: "AL-Zaina Zayid AL-Rujaibi", email: "a.rujaibi@falconstaff.org", role: "USER", designation: "Field Engineer (Trainee)", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "87", payrollNo: "E-NSE-0229", name: "Akhilesh Chopra", email: "akhilesh@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "88", payrollNo: "E-NSE-0225", name: "Fahad Hamad Ghalib", email: "fhamed@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "89", payrollNo: "L-FINT-0003", name: "Ahmed Said Al-Kabi", email: "xwm-admin-sr@xomoman.com", role: "HR", designation: "Operations Support", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "90", payrollNo: "XOM-0056", name: "Mohammed Saif Al Busaidi", email: "mbusaidi@xomoman.com", role: "MANAGEMENT", designation: "Supply Chain & Administration Manager", businessUnit: "XOM LLC", status: "Active" },
  { id: "91", payrollNo: "FAL-FWM-SUB-003", name: "Sajid Majid", email: "sajid.majeed@barikgroup.com", role: "USER", designation: "Operations Support", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "92", payrollNo: "FAL-FWM-SUB-002", name: "Praveen Kumar", email: "qhse02.bg@barikgroup.com", role: "USER", designation: "HSE Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "93", payrollNo: "FAL-FWM-SUB-001", name: "Harish VC", email: "harish.vc@barikgroup.com", role: "USER", designation: "Operations Support", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "94", payrollNo: "L-FWM-0049", name: "Abdallah Ali Mohammed Al Busaidy", email: "abusaidi@xomoman.com", role: "USER", designation: "HSE Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "95", payrollNo: "L-FINT003", name: "Ahmed Al Kaabi", email: "a.alkaabi@falconstaff.org", role: "HR", designation: "Admin and HR", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "96", payrollNo: "E-NSE-0216", name: "Waqas Ahmed", email: "awaqas@falconstaff.org", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "97", payrollNo: "E-FIN-0043", name: "Aziza Said Al Bimany", email: "abimani@falconofs.com", role: "HR", designation: "Administrator Assistant", businessUnit: "XOM LLC", status: "Inactive" },
  { id: "98", payrollNo: "LFINT00025", name: "Sabra Saud AL-Tiwaniy", email: "falcon.hr@falconstaff.org", role: "HR", designation: "Admin and HR", businessUnit: "XOM LLC", status: "Active" },
  { id: "99", payrollNo: "E-FIN-0045", name: "Ali Nemati", email: "anemati@falconofs.com", role: "SITE MANAGER", designation: "supply chain officer", businessUnit: "XOM Oman", status: "Inactive" },
  { id: "100", payrollNo: "L-HIR-0060", name: "Ali Salim Al Aisri", email: "alimatata88@hotmail.com", role: "USER", designation: "Senior Field Operator", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "101", payrollNo: "L-HIR-0055", name: "Musaab Mubarak Al Musheifri", email: "mr.musaab1986@gmail.com", role: "USER", designation: "Senior Field Operator", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "102", payrollNo: "L-FDS-0036", name: "Said Masoud Al Khusaibi", email: "skhusaibi@falconinvs.com", role: "SITE MANAGER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "103", payrollNo: "L-XOM-0049", name: "Arwa Nasser AL-Habsi", email: "anasser@xomoman.com", role: "HSE ADMIN", designation: "HSE Advisor", businessUnit: "XOM Oman", status: "Active" },
  { id: "104", payrollNo: "L-HIR-0114", name: "Ahmed Badar Al Jabri", email: "ahmedaljabri@falconstaff.org", role: "HSE", designation: "HSE Advisor", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "105", payrollNo: "L-HIR-0051", name: "Abdullah Saleh Al Farqani", email: "mkn-workshop@falconofs.com", role: "USER", designation: "Mukaizna Workshop Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "106", payrollNo: "L-FWM-0075", name: "Mohammed Abdullah Salim Al Naamani", email: "mnaamani@falconofs.com", role: "USER", designation: "WL Field Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "107", payrollNo: "L-NSE-0025", name: "Khalid Said Al Abri", email: "kabri@falconofs.com", role: "USER", designation: "Watchman", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "108", payrollNo: "L-NSE-0002", name: "Ali Mansoor Al Toubi", email: "atoubi@falconofs.com", role: "USER", designation: "Watchman", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "109", payrollNo: "L-FWM-0076", name: "Mohammed Saleh Saif Al Zakwani", email: "fwm-sr-pce@falconofs.com", role: "USER", designation: "Tool Technician", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "110", payrollNo: "E-SHE-0001", name: "Fouad Ibrahim", email: "fibrahim@falconofs.com", role: "MANAGEMENT", designation: "Technical Director", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "111", payrollNo: "L-FIN-0035", name: "Safa Mohammed Al Shukaili", email: "sshukaili@falconofs.com", role: "USER", designation: "supply chain officer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "112", payrollNo: "L-FWM-0084", name: "Sami Sulaiman Nasser Al Salehi", email: "samissn20005@gmail.com", role: "USER", designation: "Slickline Trainee Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "113", payrollNo: "L-FWM-0122", name: "Saif Salim Al-Habsi", email: "srashdi@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "114", payrollNo: "L-FWM-0011", name: "Said Hamed Said Al Dhawi", email: "sdhawi@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "115", payrollNo: "L-FWM-0115", name: "Mohammed Salim Sultan Al Hashmi", email: "mhashmi@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "116", payrollNo: "E-FWM-0099", name: "Imran Khan", email: "ikhan@falconofs.com", role: "USER", designation: "Slickline Senior Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "117", payrollNo: "E-HIR-0099", name: "Brahim Ben Mansour", email: "bbrahim@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "118", payrollNo: "E-HIR-0096", name: "Ahmed Alyan Raffie Mohammed", email: "amohammed@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "119", payrollNo: "E-FWM-0098", name: "Abdulelah Hezam Masood Al Dhubhani", email: "adhubhani@falconofs.com", role: "USER", designation: "Slickline Senior Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "120", payrollNo: "E-HIR-0098", name: "Abderrahman Aouarib", email: "aaouarib@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "121", payrollNo: "E-NSE-0003", name: "Sayed Kamal", email: "sawad@falconofs.com", role: "USER", designation: "Senior Sales Consultant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "122", payrollNo: "E-HIR-0068", name: "Muhammad Sohrab", email: "msohrab@falconofs.com", role: "USER", designation: "Senior Sales Consultant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "123", payrollNo: "E-NSE-0052", name: "Oussama Mohamed Shrebati", email: "oshrebati@falconofs.com", role: "SITE MANAGER", designation: "Sales & Technical Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "124", payrollNo: "L-FIN-0031", name: "Abdul aziz Sultan Al Farsi", email: "afarsi@xomoman.com", role: "SITE MANAGER", designation: "Sales & Marketing Manager", businessUnit: "XOM Drilling System", status: "Inactive" },
  { id: "125", payrollNo: "L-NSE-0118", name: "Ammar Said Al Azwani", email: "aazwani@falconofs.com", role: "USER", designation: "Workshop Admin Assistant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "126", payrollNo: "E-FIN-0033", name: "Saheed Tayo Oseni", email: "soseni@xomoman.com", role: "MASTER USER", designation: "QHSE Manager", businessUnit: "XOM Oman", status: "Active" },
  { id: "127", payrollNo: "L-FIN-0007", name: "Hamed Amur Al Hajri", email: "hhajri@falconofs.com", role: "USER", designation: "Public Relation Officer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "128", payrollNo: "L-FIN-0027", name: "Huda Rashid Al Harthi", email: "huda.alharthi@falconofs.com", role: "USER", designation: "Personal Assistant", businessUnit: "XOM LLC", status: "Active" },
  { id: "129", payrollNo: "E-HIR-0089", name: "Ian Jude Gonsalves", email: "igonsalves@falconofs.com", role: "USER", designation: "Operator Trainer", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "130", payrollNo: "E-HIR-0008", name: "Bruce Alexander Dsouza", email: "bdsouza@falconofs.com", role: "USER", designation: "Operator Trainer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "131", payrollNo: "L-FDS-0018", name: "Ruqaiya Abdul Rahman AlAbri", email: "rabri@falconinvs.com", role: "USER", designation: "Operations Support", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "132", payrollNo: "E-HIR-0120", name: "Emad Abdel Monem Rashad", email: "ezaki@falconofs.com", role: "SITE MANAGER", designation: "Operations Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "133", payrollNo: "L-FWM-0016", name: "Zahir Said Hamed Al Touqi", email: "ztouqi@falconofs.com", role: "USER", designation: "Senior NCP Field Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "134", payrollNo: "L-FWM-0112", name: "Waleed Saleem Thaleth Al Omairi", email: "walomairi4@gmail.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "135", payrollNo: "L-FWM-0079", name: "Said Abdullah Ali Al Mahrouqi", email: "smahrouqi@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "136", payrollNo: "L-FWM-0038", name: "Salim Saif Rashid Al Jassasi", email: "sjassasi@falconofs.com", role: "USER", designation: "Senior NCP Field Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "137", payrollNo: "L-FWM-0114", name: "Khalfan Sulaiman Hamed Al Shuaili", email: "khalfan4321@gmail.com", role: "USER", designation: "Base Manager", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "138", payrollNo: "L-FWM-0072", name: "Khalid Nasser Salim Al Hakmani", email: "khakmani@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "139", payrollNo: "L-FWM-0073", name: "Khanafour Said Hamed Al Dari", email: "kdarai@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "140", payrollNo: "L-FWM-0030", name: "Ismail Salim Ali Al Mani", email: "imani@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "141", payrollNo: "L-FWM-0070", name: "Ibrahim Mohamed Saif Al Hudaifi", email: "ihadaifi@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "142", payrollNo: "L-FWM-0025", name: "Hamed Al Saghir Humaid Al Maharbi", email: "hmaharbi@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "143", payrollNo: "L-FWM-0051", name: "Abdullah Saleh Ali Al Yahyaee", email: "ayahyaee@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "144", payrollNo: "L-FWM-0020", name: "Ahmed Rabia Obaid Al Rawahi", email: "arawahi@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "145", payrollNo: "L-FWM-0058", name: "Ali Mohamed Murad Al Bulushi", email: "ambalushi@falconofs.com", role: "USER", designation: "NCP Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "146", payrollNo: "L-FWM-0045", name: "Yasser Saif Mohammed Al Majarafi", email: "ymajarafi@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "147", payrollNo: "L-FWM-0081", name: "Saif Ali Said Al Shamli", email: "sshamli@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "148", payrollNo: "L-FWM-0043", name: "Sultan Mohammed Hamood Al Gaithi", email: "sghaithi@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "149", payrollNo: "L-FWM-0082", name: "Salim Obaid Mohammed Al Durey", email: "sdurei@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "150", payrollNo: "L-FWM-0083", name: "Salim Said Mohammed Al Burtamani", email: "sburtamani@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "151", payrollNo: "L-FWM-0018", name: "Mohammed Ahmed Said Al Rawahi", email: "mrawahi@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "152", payrollNo: "L-FWM-0065", name: "Hamed Sulaiman Said Al Raqami", email: "hraqami@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "153", payrollNo: "L-FWM-0067", name: "Hashil Humaid Mohammed Amri", email: "hamri@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "154", payrollNo: "L-FWM-0022", name: "Abdullah Said Hamood Al Waihibi", email: "awuhaibi@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "155", payrollNo: "L-FWM-0086", name: "Saud Said Hamood Al Shabibi", email: "ashabibi@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "156", payrollNo: "L-FWM-0050", name: "Abdullah Said Salim Al Hinai", email: "ahinai@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "157", payrollNo: "L-FWM-0053", name: "Ahmed Hamed Nasser Al Aghbari", email: "aaghbari@falconofs.com", role: "USER", designation: "NCP Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "158", payrollNo: "L-FWM-0041", name: "Sulaiman Nasser Mattar Al Masqari", email: "smasqari@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "159", payrollNo: "L-FWM-0012", name: "Sultan Khamis Mohsin Al Busaidi", email: "sbusaidi@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "160", payrollNo: "L-FWM-0039", name: "Salim Khalfan Hamed Al Bahlouli", email: "sbahlouli@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "161", payrollNo: "L-FWM-0077", name: "Musalem Abdullah Al Mukhaini", email: "mmukhaini@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "162", payrollNo: "L-FWM-0031", name: "Khamis Salim Thani Al Busaidi", email: "kbusaidi@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "163", payrollNo: "L-FWM-0064", name: "Hamdan Mohammed Salim Al Qanoobi", email: "hqanoobi@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "164", payrollNo: "L-FWM-0023", name: "Badar Nasser Said Al Hadiwi", email: "bhadaiwi@falconofs.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "165", payrollNo: "L-HIR-0083", name: "Ali Salim Ali Al Sawafi", email: "alialsawafi26@gmail.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "166", payrollNo: "L-FWM-0055", name: "Ahmed Musabah Ali Al Quraini", email: "ahmed6870@gmail.com", role: "USER", designation: "NCP Assistant", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "167", payrollNo: "E-FWM-0104", name: "Gibi John", email: "gibijohn@falconofs.com", role: "USER", designation: "NCP / Fbl Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "168", payrollNo: "L-FWM-0036", name: "Saif Said Nasser Al Rashdi", email: "fwm-sr-bm@falconstaff.org", role: "USER", designation: "MPLT Engineer", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "169", payrollNo: "L-FWM-0066", name: "Hamood Mohammed Marzouq Al Badi", email: "hamoodalbadi@gmail.com", role: "SITE MANAGER", designation: "MPLT Engineer", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "170", payrollNo: "L-NSE-0132", name: "Khamis Said Al Amri", email: "khamri@falconofs.com", role: "USER", designation: "Mechanic", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "171", payrollNo: "E-FWM-0108", name: "Jagannatha Achary", email: "jagas84@gmail.com", role: "USER", designation: "Mechanic", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "172", payrollNo: "L-HIR-0092", name: "Moosa Nasser Khalfan Al Fahdi", email: "afahdi@falconofs.com", role: "USER", designation: "Mechanic", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "173", payrollNo: "L-FDS-0030", name: "Sultan Salim AlHabsi", email: "shabsi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "174", payrollNo: "L-FDS-0028", name: "Mohammed Sultan Al Shabibi", email: "mshabibi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "175", payrollNo: "L-FDS-0031", name: "Muhannad Mohamed AlBalushi", email: "mbalushi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "176", payrollNo: "L-FDS-0034", name: "Fahad Khalfan Matar Al-Mazroui", email: "fmazroui@xomoman.com", role: "USER", designation: "MWD Trainee", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "177", payrollNo: "E-FDS-0004", name: "Bilal Abdullah Malik", email: "bmalik@xomoman.com", role: "USER", designation: "Measurement & Logging While Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "178", payrollNo: "L-FDS-0015", name: "Ahmed Mohammed Said Al-omairi", email: "aomairi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "179", payrollNo: "L-SHE-0001", name: "Zahran Al Aufi", email: "zoufi@falconofs.com", role: "MANAGEMENT", designation: "Managing Director", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "180", payrollNo: "L-FWM-0091", name: "Yaqoob Awadh Salim Al Hinai", email: "fwm-sr-mechanic@falconofs.com", role: "USER", designation: "Maintenance Supervisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "181", payrollNo: "L-FDS-0006", name: "Ali Khalifa Al-Ismaili", email: "akismaili@xomoman.com", role: "SITE MANAGER", designation: "Maintenance Manager", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "182", payrollNo: "E-NSEC-0001", name: "vahed goudarzi", email: "vgoudarzi@falconstaff.org", role: "USER", designation: "Log analyst", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "183", payrollNo: "L-FWM-0063", name: "Hamad Said Amour Batrani", email: "hbatrani@falconofs.com", role: "USER - JM", designation: "Journey manager / store keeper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "184", payrollNo: "L-FIN-0034", name: "Zakiya Salim Al Naabi", email: "znaabi@falconofs.com", role: "HSE ADMIN", designation: "HSE-HR Admin Assistant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "185", payrollNo: "HSE FWM", name: "HSE FWM", email: "fwm-sr-hse@falconofs.com", role: "HSE", designation: "HSE Advisor", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "186", payrollNo: "L-HIR-0115", name: "Zakariya Yahya Al Busaidi", email: "zbusaidi@xomoman.com", role: "HSE ADMIN", designation: "HSE Advisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "187", payrollNo: "L-FWM-0033", name: "Mohammed Humaid Salim Al Alawi", email: "malawi@xomoman.com", role: "HSE", designation: "HSE Advisor", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "188", payrollNo: "L-FIN-0019", name: "Mohamed Abdullah Al Shukaili", email: "mashukaili@falconofs.com", role: "HR", designation: "HR Manager", businessUnit: "XOM LLC", status: "Inactive" },
  { id: "189", payrollNo: "L-NSE-0238", name: "Riam Zaid Al Saadi", email: "riyam@falconofs.com", role: "HR", designation: "HR Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "190", payrollNo: "L-FIN-0038", name: "Hanan Ahmed Al Shuhaibi", email: "hshuhaibi@falconstaff.org", role: "HR", designation: "HR Assistant", businessUnit: "XOM LLC", status: "Inactive" },
  { id: "191", payrollNo: "L-HIR-0142", name: "Muntasar Salem Alomiri", email: "montasr007@gmail.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "192", payrollNo: "L-HIR-0034", name: "Muayid Khalid Said Al Mudhaffar", email: "mmudhaffar@falconofs.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "193", payrollNo: "L-HIR-0144", name: "Bader Abdullah AlRusheidi", email: "bader2988@gmail.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "194", payrollNo: "L-HIR-0143", name: "Haitham Ahmed AlMahmoodi", email: "atm911atm@yahoo.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "195", payrollNo: "L-HIR-0064", name: "Ali Salim Saleh Al Oraimi", email: "aoraimi@falconofs.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "196", payrollNo: "L-HIR-0084", name: "Ahmed Maktoum Maayouf AL Khamisi", email: "akhamisi@falconofs.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "197", payrollNo: "L-HIR-0090", name: "Ashraf Sulaiyam Khalfan Al Alawi", email: "allwyashrf82@gmail.com", role: "USER", designation: "Helper", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "198", payrollNo: "L-NSE-0183", name: "Salim Ali Al Shaqsi", email: "sshaqsi@falconofs.com", role: "USER", designation: "Gun Loader - Trainee", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "199", payrollNo: "L-NSE-0105", name: "Saad Sabaiyah Al Nofli", email: "snofli@falconofs.com", role: "USER", designation: "Gun Loader", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "200", payrollNo: "L-NSE-0093", name: "Rashid Saif Al Sawafi", email: "rsawafi@falconofs.com", role: "USER", designation: "Gun Loader", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "201", payrollNo: "L-FIN-0028", name: "Hilal Ali Al Kalbani", email: "hilal.alkalbani@falconinvs.com", role: "MANAGEMENT", designation: "General Manager", businessUnit: "XOM LLC", status: "Active" },
  { id: "202", payrollNo: "L-FWM-0017", name: "Amor Ali Salim Al Shukairi", email: "ashukairi@falconofs.com", role: "USER", designation: "Gauge Engineer", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "203", payrollNo: "L-NSE-0190", name: "Hamed Mohammed Al Kindi", email: "hkindi@falconofs.com", role: "USER", designation: "FQA Gun Shop Supervisor", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "204", payrollNo: "L-FWM-0095", name: "Salim Khalifa Hilal Al Mashaikhi", email: "smashaikhi@falconofs.com", role: "USER", designation: "Fork Lift Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "205", payrollNo: "L-FWM-0093", name: "Hamed Salim Hamed Al Madhoushi", email: "hmadhoushi@falconofs.com", role: "USER", designation: "Fork Lift Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "206", payrollNo: "E-FIN-0032", name: "Jibu Varghese", email: "jvarghese@xomoman.com", role: "USER", designation: "Finance manager", businessUnit: "XOM LLC", status: "Active" },
  { id: "207", payrollNo: "L-HIR-0033", name: "Waleed Mubarak Said Al Matani", email: "wmatani@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "208", payrollNo: "L-HIR-0066", name: "Mohammed Said Ali Al Aufi", email: "maufi@falconofs.com", role: "USER", designation: "Slickline Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "209", payrollNo: "L-NSE-0172", name: "Sultan Saif Al Alawi", email: "salawi@falconofs.com", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "210", payrollNo: "L-NSE-0178", name: "Adil Ali Al Riyami", email: "aariyami@falconofs.com", role: "USER", designation: "Senior Field Operator", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "211", payrollNo: "E-HIR-0116", name: "Shujaat Ali Khan", email: "salikhan@falconofs.com", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "212", payrollNo: "E-NSE-0037", name: "Rhike Arifka", email: "rarifka@falconofs.com", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "213", payrollNo: "E-HIR-0077", name: "Farrukh Hameed", email: "fhameed@falconofs.com", role: "USER", designation: "Field Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "214", payrollNo: "L-NSE-0004", name: "Ahmed Al Hashmi", email: "ahashmi@falconofs.com", role: "USER", designation: "Workshop Foremen", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "215", payrollNo: "E-NSE-0026", name: "Muchtar Mochamed", email: "muchtar@falconofs.com", role: "SITE MANAGER", designation: "Engineer In Charge", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "216", payrollNo: "E-FDS-0043", name: "Joao Luis Fernandes", email: "jluis@xomoman.com", role: "USER", designation: "Electronics Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "217", payrollNo: "L-FDS-0035", name: "Ayman Ali Saleh Al-Mazroui", email: "aalmazroui@xomoman.com", role: "USER", designation: "Electronics Technician", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "218", payrollNo: "E-FWM-0105", name: "Sharath Kumar", email: "skumar@falconofs.com", role: "USER", designation: "Electrician", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "219", payrollNo: "L-FWM-0088", name: "Sulaiyam Salim Saif Al Daraiee", email: "sduree@falconofs.com", role: "USER", designation: "Driver (HD)", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "220", payrollNo: "L-FDS-0001", name: "Suhail Ahmed Tabouk", email: "stabouk@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "221", payrollNo: "L-FDS-0008", name: "Said Sulaiman AlHoqani", email: "shoqani@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "222", payrollNo: "L-FDS-0020", name: "Nasser Khamis AlRawahi", email: "nrawahi@xomoman.com", role: "USER", designation: "Directional Driller Trainee", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "223", payrollNo: "L-FDS-0029", name: "Al Makhtar Masaaod Al-Adawi", email: "madawi@xomoman.com", role: "USER", designation: "Operations Support", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "224", payrollNo: "L-FDS-0002", name: "Khalid Zahran Busaidi", email: "kzbusaidi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "225", payrollNo: "L-FDS-0025", name: "Khalid Juma ALOraimi", email: "koraimi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "226", payrollNo: "L-FDS-0016", name: "Khalid Nasser AlBusaidi", email: "knbusaidi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "227", payrollNo: "L-FDS-0012", name: "Idris Surur AlAlawi", email: "ialawi@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "228", payrollNo: "L-FDS-0013", name: "Hosni Mubarak Al-Amri", email: "hamri@xomoman.com", role: "USER", designation: "Directional Drilling Engineer", businessUnit: "XOM Drilling System", status: "Active" },
  { id: "229", payrollNo: "00012", name: "I A Xom", email: "xom870@xomoman.com", role: "HSE", designation: "Admin and HR", businessUnit: "XOM Oman", status: "Active" },
  { id: "230", payrollNo: "L-HIR-0079", name: "Abdullah Hilal Al Ismaili", email: "ahismaili@falconofs.com", role: "USER", designation: "Desk Engineer", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "231", payrollNo: "L-FWM-0002", name: "Said Mohamed Said Al Zakwani", email: "szakwani@xomoman.com", role: "SITE MANAGER", designation: "Operations Manager", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "232", payrollNo: "L-NSE-0196", name: "Yahya Ahmed Al Busaidi", email: "ybusaidi@falconofs.com", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "233", payrollNo: "L-NSE-0124", name: "Wagdi Suleyim Al Hinai", email: "whinai@falconofs.com", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "234", payrollNo: "L-NSE-0174", name: "Issa Saleh Al Amri", email: "iamri@falconofs.com", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "235", payrollNo: "L-NSE-0176", name: "Ahmed Mattar Al Qamshooey", email: "aqamshooey@falconofs.com", role: "USER", designation: "Crew Chief", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "236", payrollNo: "E-NSE-0049", name: "Jatinderjit Singh", email: "jsingh@falconofs.com", role: "USER", designation: "Crane Operator", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "237", payrollNo: "E-FWM-0120", name: "Hemza Benchelloug", email: "hbenchelloug@falconofs.com", role: "SITE MANAGER", designation: "Client Services Engineer", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "238", payrollNo: "L-NSE-0191", name: "Mohammed Salim Al Barashdi", email: "mbarashdi@xomoman.com", role: "MANAGEMENT", designation: "Chief Operating Officer", businessUnit: "XOM Oman", status: "Active" },
  { id: "239", payrollNo: "L-NSE-0079", name: "Nasser Humaid Al Harrasi", email: "nharrasi@falconofs.com", role: "USER", designation: "Cable Specialist", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "240", payrollNo: "L-FWM-0089", name: "Sultan Abdullah Al Tawqi", email: "stawqi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "241", payrollNo: "L-FWM-0044", name: "Sultan Said Saif Said Al Maamari", email: "smaamari@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "242", payrollNo: "L-FWM-0087", name: "Sulaiman Musabah Khamis Al Ghafri", email: "sghafri@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "243", payrollNo: "L-FWM-0085", name: "Sanad Rashid Masoud Al Aliyani", email: "saliyani@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "244", payrollNo: "L-FWM-0078", name: "Rashid Salim Rashid Al Junaibi", email: "rjunaibi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "245", payrollNo: "L-FWM-0009", name: "Rashid Mohammed Khasib Al Bakri", email: "rbakri@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "246", payrollNo: "L-FWM-0013", name: "Naseer Khalfan Masoud Al Habesi", email: "nhabsi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "247", payrollNo: "L-FWM-0007", name: "Mohammed Abdullah Hamdan Al Nasseri", email: "mnasseri@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "248", payrollNo: "L-FWM-0071", name: "Jasim Khazam Said Al Sulaimi", email: "jsulaimi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "249", payrollNo: "L-FWM-0026", name: "Hamed Ali Sulaiyim Al Syabi", email: "hsiyabi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "250", payrollNo: "L-FWM-0029", name: "Humid Mubarak Humid Al Jabri", email: "hjabri@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "251", payrollNo: "L-HIR-0146", name: "Hamid Said Mohammed Al Gahaffi", email: "hamadsaidmuhammad@gmail.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "252", payrollNo: "L-FWM-0059", name: "Ashraf Khalaf Khalfan Al Musallami", email: "amusallami@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "253", payrollNo: "L-FWM-0047", name: "Ali Abdullah Humaid Al Kalbani", email: "akalbani@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "254", payrollNo: "L-FWM-0054", name: "Ahmed Khalfan Salim Al Hazami", email: "ahizami@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "255", payrollNo: "L-FWM-0056", name: "Ali Ahmed Adam Al Bulushi", email: "ahbalushi@falconofs.com", role: "USER", designation: "Tool Technician", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "256", payrollNo: "L-FWM-0052", name: "Abdullah Sulaiman Al Brashdi", email: "abrashdi@falconofs.com", role: "USER", designation: "Assistant WL Operator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "257", payrollNo: "E-HIR-0071", name: "Prasenjit Mondal", email: "pmondal@falconofs.com", role: "SITE MANAGER", designation: "Asset Assurance Manager", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "258", payrollNo: "L-FIN-0036", name: "Sufya Ahmed Al Riyami", email: "sriyami@falconofs.com", role: "HR", designation: "Administrator Assistant", businessUnit: "Falcon Oilfield Services", status: "Inactive" },
  { id: "259", payrollNo: "L-FIN-0045", name: "Hajer salim Al Sharji", email: "hajar.alsharji199555@gmail.com", role: "HR", designation: "Administrator Assistant", businessUnit: "XOM LLC", status: "Active" },
  { id: "260", payrollNo: "L-FWM-0032", name: "Mohammed Said Sulaiyam Alabri", email: "mabri@falconofs.com", role: "HR", designation: "Administrator", businessUnit: "XOM Well Maintenance", status: "Active" },
  { id: "261", payrollNo: "L-HIR-0145", name: "Khalid Mattar AL Saaidi", email: "khalid.alsaaidi@outlook.com", role: "HR", designation: "Admin and HR", businessUnit: "XOM Well Maintenance", status: "Inactive" },
  { id: "262", payrollNo: "E-FIN-0039", name: "Ebin John", email: "ebin.john@falconinvs.com", role: "USER", designation: "Accountant", businessUnit: "XOM LLC", status: "Active" },
  { id: "263", payrollNo: "E-FIN-0021", name: "Ahsan Sajjad", email: "ahsan@falconinvs.com", role: "USER", designation: "Accountant", businessUnit: "XOM LLC", status: "Active" },
  { id: "264", payrollNo: "E-NSE-0004", name: "Arunangshu Banerjee", email: "abanerjee@falconofs.com", role: "USER", designation: "Accountant", businessUnit: "Falcon Oilfield Services", status: "Active" },
  { id: "265", payrollNo: "ADMIN", name: "Syed Sadaqat ADMIN", email: "xom-himaya@falconinvs.com", role: "ADMIN SYSTEM", designation: "Accountant Treasury", businessUnit: "XOM Oman", status: "Active" },
]

export const businessUnits = [
  "XOM Drilling System",
  "Falcon Oilfield Services",
  "XOM Well Maintenance",
  "XOM Oman",
  "XOM LLC",
]

export const roles = [
  "ADMIN SYSTEM",
  "MANAGEMENT",
  "SITE MANAGER",
  "SITE MANAGER - Global",
  "HSE ADMIN",
  "HSE",
  "HR",
  "MASTER USER",
  "USER",
  "USER - JM",
]
