[CmdletBinding()]
param([string]$Server = 'localhost\SQLEXPRESS', [string]$Database = 'Aegis_XOM', [string]$OutputDirectory = "$PWD\Aegis_XOM_Export")
$ErrorActionPreference = 'Stop'
$connection = New-Object System.Data.SqlClient.SqlConnection
$connection.ConnectionString = "Server=$Server;Database=$Database;Integrated Security=True;TrustServerCertificate=True;Application Name=AegisReadOnlyExport"
function Invoke-ReadOnly([string]$Sql) { $command = $connection.CreateCommand(); $command.CommandText = $Sql; $command.CommandTimeout = 0; $reader = $command.ExecuteReader(); $table = New-Object System.Data.DataTable; $table.Load($reader); $reader.Dispose(); $command.Dispose(); return $table }
function Convert-Value($Value) { if ($Value -is [System.DBNull]) { return $null }; if ($Value -is [datetime] -or $Value -is [datetimeoffset]) { return $Value.ToString('o') }; if ($Value -is [guid]) { return $Value.ToString() }; if ($Value -is [decimal] -or $Value -is [double] -or $Value -is [single]) { return $Value.ToString([Globalization.CultureInfo]::InvariantCulture) }; return $Value }
function Rows-Json($Table) { $items = @(); foreach ($row in $Table.Rows) { $object = [ordered]@{}; foreach ($column in $Table.Columns) { $object[$column.ColumnName] = Convert-Value $row[$column.ColumnName] }; $items += [pscustomobject]$object }; return $items }
function Write-Json($Path, $Value) { [IO.File]::WriteAllText($Path, ($Value | ConvertTo-Json -Depth 20), (New-Object Text.UTF8Encoding($false))) }
if (Test-Path $OutputDirectory) { Remove-Item $OutputDirectory -Recurse -Force }; New-Item $OutputDirectory -ItemType Directory | Out-Null; New-Item "$OutputDirectory\table_data" -ItemType Directory | Out-Null
try { $connection.Open(); $db = Invoke-ReadOnly "SELECT DB_NAME() database_name, CAST(SERVERPROPERTY('ProductVersion') AS nvarchar(100)) sql_server_version, CAST(SERVERPROPERTY('Edition') AS nvarchar(200)) edition"; Write-Json "$OutputDirectory\database_metadata.json" (Rows-Json $db); Write-Host "Connected read-only to $Server / $Database" }
catch { Write-Error "FAILED CONNECTION: $($_.Exception.Message)"; exit 1 }
$queries = [ordered]@{
 tables = "SELECT s.name schema_name,t.name table_name,SUM(CASE WHEN p.index_id IN (0,1) THEN p.rows ELSE 0 END) row_count FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id LEFT JOIN sys.partitions p ON p.object_id=t.object_id WHERE t.is_ms_shipped=0 GROUP BY s.name,t.name ORDER BY s.name,t.name"
 columns = "SELECT s.name schema_name,t.name table_name,c.column_id column_order,c.name column_name,ty.name data_type,c.max_length,c.precision,c.scale,c.is_nullable,c.is_identity,c.is_computed,dc.definition default_definition FROM sys.columns c JOIN sys.tables t ON t.object_id=c.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.types ty ON ty.user_type_id=c.user_type_id LEFT JOIN sys.default_constraints dc ON dc.parent_object_id=c.object_id AND dc.parent_column_id=c.column_id WHERE t.is_ms_shipped=0 ORDER BY s.name,t.name,c.column_id"
 primary_keys = "SELECT s.name schema_name,t.name table_name,kc.name constraint_name,c.name column_name,ic.key_ordinal column_order FROM sys.key_constraints kc JOIN sys.tables t ON t.object_id=kc.parent_object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.index_columns ic ON ic.object_id=kc.parent_object_id AND ic.index_id=kc.unique_index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE kc.type='PK' ORDER BY s.name,t.name,kc.name,ic.key_ordinal"
 foreign_keys = "SELECT ps.name source_schema,pt.name source_table,pc.name source_column,rs.name target_schema,rt.name target_table,rc.name target_column,fk.name constraint_name FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id JOIN sys.tables pt ON pt.object_id=fk.parent_object_id JOIN sys.schemas ps ON ps.schema_id=pt.schema_id JOIN sys.columns pc ON pc.object_id=fkc.parent_object_id AND pc.column_id=fkc.parent_column_id JOIN sys.tables rt ON rt.object_id=fk.referenced_object_id JOIN sys.schemas rs ON rs.schema_id=rt.schema_id JOIN sys.columns rc ON rc.object_id=fkc.referenced_object_id AND rc.column_id=fkc.referenced_column_id ORDER BY ps.name,pt.name,fk.name"
 indexes = "SELECT s.name schema_name,t.name table_name,i.name index_name,i.type_desc index_type,i.is_unique,ic.key_ordinal column_order,c.name column_name,ic.is_included_column FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id LEFT JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id LEFT JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE i.index_id>0 AND t.is_ms_shipped=0 ORDER BY s.name,t.name,i.name,ic.key_ordinal"
}
foreach ($name in $queries.Keys) { Write-Host "Exporting metadata: $name"; Write-Json "$OutputDirectory\$name.json" (Rows-Json (Invoke-ReadOnly $queries[$name])) }
$tables = Rows-Json (Invoke-ReadOnly $queries.tables); foreach ($table in $tables) { $n = [string]$table.table_name; $table | Add-Member -NotePropertyName classification -NotePropertyValue $(if($n -match 'history|audit|log|trail'){ 'HISTORY_AUDIT' } elseif($n -match 'user|login|password|rights|reset'){ 'USER_SECURITY' } elseif($n -match 'import|temp'){ 'IMPORT_TEMPORARY' } elseif($n -match 'notification|email|search|report|frequency'){ 'SYSTEM_LOG' } elseif($n -match 'type|status|category|severity|priority|department|location'){ 'MASTER_DATA' } else { 'BUSINESS_DATA' }) -Force }; Write-Json "$OutputDirectory\tables.json" $tables; $count = 0; $dataFiles = @(); foreach ($table in $tables) { $count++; $schema = [string]$table.schema_name; $name = [string]$table.table_name; $safe = ($schema + '__' + $name) -replace '[^A-Za-z0-9_.-]','_'; Write-Host "Exporting table $count of $($tables.Count): $schema.$name"; try { $data = Rows-Json (Invoke-ReadOnly ("SELECT * FROM " + ('['+$schema+'].['+$name+']'))); $file = "table_data\$safe.json"; Write-Json "$OutputDirectory\$file" $data; $hash = (Get-FileHash "$OutputDirectory\$file" -Algorithm SHA256).Hash.ToLower(); $dataFiles += [pscustomobject]@{table="$schema.$name";file=$file.Replace('\','/');row_count=$data.Count;column_count=if($data.Count){$data[0].PSObject.Properties.Count}else{0};sha256=$hash;exported_at=(Get-Date).ToUniversalTime().ToString('o')} } catch { Write-Error "FAILED TABLE: $schema.$name`nERROR: $($_.Exception.Message)"; $connection.Close(); exit 1 } }
$rowCounts = @($tables | ForEach-Object { [pscustomobject]@{schema_name=$_.schema_name;table_name=$_.table_name;row_count=[int64]$_.row_count} }); Write-Json "$OutputDirectory\row_counts.json" $rowCounts
$checksums = [ordered]@{}; Get-ChildItem $OutputDirectory -Recurse -File | Where-Object { $_.Name -ne 'checksums.json' } | ForEach-Object { $checksums[$_.FullName.Substring($OutputDirectory.Length+1).Replace('\','/')] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLower() }; Write-Json "$OutputDirectory\checksums.json" $checksums
$manifest = [ordered]@{format='Aegis_XOM_ReadOnly_Export_v1';database=$Database;server=$Server;exported_at=(Get-Date).ToUniversalTime().ToString('o');tables=$tables.Count;populated_tables=@($rowCounts | Where-Object row_count -gt 0).Count;empty_tables=@($rowCounts | Where-Object row_count -eq 0).Count;total_rows=[int64](($rowCounts | Measure-Object row_count -Sum).Sum);data_files=$dataFiles}; Write-Json "$OutputDirectory\manifest.json" $manifest
$zip = Join-Path (Split-Path $OutputDirectory -Parent) ((Split-Path $OutputDirectory -Leaf) + '.zip'); if(Test-Path $zip){Remove-Item $zip -Force}; Compress-Archive -Path "$OutputDirectory\*" -DestinationPath $zip -CompressionLevel Optimal; $zipHash=(Get-FileHash $zip -Algorithm SHA256).Hash.ToLower(); $connection.Close(); Write-Host "`nExport completed successfully."; Write-Host "Tables: $($tables.Count)"; Write-Host "Populated tables: $($manifest.populated_tables)"; Write-Host "Columns: $(@((Rows-Json (Invoke-ReadOnly $queries.columns)).Count))"; Write-Host "Rows: $($manifest.total_rows)"; Write-Host "Foreign keys: $(@((Rows-Json (Invoke-ReadOnly $queries.foreign_keys)).Count))"; Write-Host "Indexes: $(@((Rows-Json (Invoke-ReadOnly $queries.indexes)).Count))"; Write-Host "ZIP file: $zip"; Write-Host "SHA-256: $zipHash"
